import type { ImageSourcePropType } from 'react-native';

import type { EnemyId } from '@/data/enemies';

export type ExactlyTwenty<T> = readonly [
  T, T, T, T, T,
  T, T, T, T, T,
  T, T, T, T, T,
  T, T, T, T, T,
];

export type BlackStarReactionAssetTuple = ExactlyTwenty<ImageSourcePropType | undefined>;

/**
 * All 140 generated Black Star reaction images. Metro requires literal paths,
 * so every character keeps a fixed 20-slot tuple in catalog order.
 */
export const BLACK_STAR_GENERATED_REACTION_ASSETS = {
  magician: [
    require('../../../assets/black-stars/reactions/magician/01-startled.png'),
    require('../../../assets/black-stars/reactions/magician/02-hold-cheek.png'),
    require('../../../assets/black-stars/reactions/magician/03-protest.png'),
    require('../../../assets/black-stars/reactions/magician/04-sulk.png'),
    require('../../../assets/black-stars/reactions/magician/05-notice.png'),
    require('../../../assets/black-stars/reactions/magician/06-escape.png'),
    require('../../../assets/black-stars/reactions/magician/07-swatt.png'),
    require('../../../assets/black-stars/reactions/magician/08-stomp.png'),
    require('../../../assets/black-stars/reactions/magician/09-bawling.png'),
    require('../../../assets/black-stars/reactions/magician/10-curl.png'),
    require('../../../assets/black-stars/reactions/magician/11-frantic-no.png'),
    require('../../../assets/black-stars/reactions/magician/12-faint.png'),
    require('../../../assets/black-stars/reactions/magician/13-furious-stomp.png'),
    require('../../../assets/black-stars/reactions/magician/14-backward-escape.png'),
    require('../../../assets/black-stars/reactions/magician/15-cheek-shield.png'),
    require('../../../assets/black-stars/reactions/magician/16-floor-cling.png'),
    require('../../../assets/black-stars/reactions/magician/17-starfish-tantrum.png'),
    require('../../../assets/black-stars/reactions/magician/18-turnaway.png'),
    require('../../../assets/black-stars/reactions/magician/19-rage-shake.png'),
    require('../../../assets/black-stars/reactions/magician/20-ultimate-enough.png'),
  ],
  informant: [
    require('../../../assets/black-stars/reactions/informant/01-startled.webp'),
    require('../../../assets/black-stars/reactions/informant/02-hold-cheek.webp'),
    require('../../../assets/black-stars/reactions/informant/03-protest.webp'),
    require('../../../assets/black-stars/reactions/informant/04-sulk.webp'),
    require('../../../assets/black-stars/reactions/informant/05-notice.webp'),
    require('../../../assets/black-stars/reactions/informant/06-evade.webp'),
    require('../../../assets/black-stars/reactions/informant/07-parry.webp'),
    require('../../../assets/black-stars/reactions/informant/08-signature-counter.webp'),
    require('../../../assets/black-stars/reactions/informant/09-bawling-waterfall.webp'),
    require('../../../assets/black-stars/reactions/informant/10-defensive-curl.webp'),
    require('../../../assets/black-stars/reactions/informant/11-frantic-no.webp'),
    require('../../../assets/black-stars/reactions/informant/12-dramatic-faint.webp'),
    require('../../../assets/black-stars/reactions/informant/13-furious-stomp.webp'),
    require('../../../assets/black-stars/reactions/informant/14-backward-escape.webp'),
    require('../../../assets/black-stars/reactions/informant/15-cheek-shield.webp'),
    require('../../../assets/black-stars/reactions/informant/16-floor-cling.webp'),
    require('../../../assets/black-stars/reactions/informant/17-starfish-tantrum.webp'),
    require('../../../assets/black-stars/reactions/informant/18-offended-turnaway.webp'),
    require('../../../assets/black-stars/reactions/informant/19-tiny-rage-shake.webp'),
    require('../../../assets/black-stars/reactions/informant/20-ultimate-enough.webp'),
  ],
  tracker: [
    require('../../../assets/black-stars/reactions/tracker/01-startled.webp'),
    require('../../../assets/black-stars/reactions/tracker/02-hold-cheek.webp'),
    require('../../../assets/black-stars/reactions/tracker/03-protest.webp'),
    require('../../../assets/black-stars/reactions/tracker/04-sulk.webp'),
    require('../../../assets/black-stars/reactions/tracker/05-notice.webp'),
    require('../../../assets/black-stars/reactions/tracker/06-evade.webp'),
    require('../../../assets/black-stars/reactions/tracker/07-parry.webp'),
    require('../../../assets/black-stars/reactions/tracker/08-signature-counter.webp'),
    require('../../../assets/black-stars/reactions/tracker/09-bawling-waterfall.webp'),
    require('../../../assets/black-stars/reactions/tracker/10-defensive-curl.webp'),
    require('../../../assets/black-stars/reactions/tracker/11-frantic-no.webp'),
    require('../../../assets/black-stars/reactions/tracker/12-dramatic-faint.webp'),
    require('../../../assets/black-stars/reactions/tracker/13-furious-stomp.webp'),
    require('../../../assets/black-stars/reactions/tracker/14-backward-escape.webp'),
    require('../../../assets/black-stars/reactions/tracker/15-cheek-shield.webp'),
    require('../../../assets/black-stars/reactions/tracker/16-floor-cling.webp'),
    require('../../../assets/black-stars/reactions/tracker/17-starfish-tantrum.webp'),
    require('../../../assets/black-stars/reactions/tracker/18-offended-turnaway.webp'),
    require('../../../assets/black-stars/reactions/tracker/19-tiny-rage-shake.webp'),
    require('../../../assets/black-stars/reactions/tracker/20-ultimate-enough.webp'),
  ],
  safecracker: [
    require('../../../assets/black-stars/reactions/safecracker/01-startled.webp'),
    require('../../../assets/black-stars/reactions/safecracker/02-hold-cheek.webp'),
    require('../../../assets/black-stars/reactions/safecracker/03-protest.webp'),
    require('../../../assets/black-stars/reactions/safecracker/04-sulk.webp'),
    require('../../../assets/black-stars/reactions/safecracker/05-notice.webp'),
    require('../../../assets/black-stars/reactions/safecracker/06-evade.webp'),
    require('../../../assets/black-stars/reactions/safecracker/07-parry.webp'),
    require('../../../assets/black-stars/reactions/safecracker/08-signature-counter.webp'),
    require('../../../assets/black-stars/reactions/safecracker/09-bawling-waterfall.webp'),
    require('../../../assets/black-stars/reactions/safecracker/10-defensive-curl.webp'),
    require('../../../assets/black-stars/reactions/safecracker/11-frantic-no.webp'),
    require('../../../assets/black-stars/reactions/safecracker/12-dramatic-faint.webp'),
    require('../../../assets/black-stars/reactions/safecracker/13-furious-stomp.webp'),
    require('../../../assets/black-stars/reactions/safecracker/14-backward-escape.webp'),
    require('../../../assets/black-stars/reactions/safecracker/15-cheek-shield.webp'),
    require('../../../assets/black-stars/reactions/safecracker/16-floor-cling.webp'),
    require('../../../assets/black-stars/reactions/safecracker/17-starfish-tantrum.webp'),
    require('../../../assets/black-stars/reactions/safecracker/18-offended-turnaway.webp'),
    require('../../../assets/black-stars/reactions/safecracker/19-tiny-rage-shake.webp'),
    require('../../../assets/black-stars/reactions/safecracker/20-ultimate-enough.webp'),
  ],
  'veiled-duchess': [
    require('../../../assets/black-stars/reactions/veiled-duchess/01-startled.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/02-hold-cheek.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/03-protest.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/04-sulk.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/05-notice.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/06-evade.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/07-parry.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/08-signature-counter.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/09-bawling-waterfall.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/10-defensive-curl.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/11-frantic-no.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/12-dramatic-faint.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/13-furious-stomp.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/14-backward-escape.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/15-cheek-shield.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/16-floor-cling.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/17-starfish-tantrum.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/18-offended-turnaway.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/19-tiny-rage-shake.webp'),
    require('../../../assets/black-stars/reactions/veiled-duchess/20-ultimate-enough.webp'),
  ],
  courier: [
    require('../../../assets/black-stars/reactions/courier/01-startled.png'),
    require('../../../assets/black-stars/reactions/courier/02-hold-cheek.png'),
    require('../../../assets/black-stars/reactions/courier/03-protest.png'),
    require('../../../assets/black-stars/reactions/courier/04-sulk.png'),
    require('../../../assets/black-stars/reactions/courier/05-notice.png'),
    require('../../../assets/black-stars/reactions/courier/06-evade.png'),
    require('../../../assets/black-stars/reactions/courier/07-parry.png'),
    require('../../../assets/black-stars/reactions/courier/08-signature-counter.png'),
    require('../../../assets/black-stars/reactions/courier/09-bawling-waterfall.png'),
    require('../../../assets/black-stars/reactions/courier/10-defensive-curl.png'),
    require('../../../assets/black-stars/reactions/courier/11-frantic-no.png'),
    require('../../../assets/black-stars/reactions/courier/12-dramatic-faint.png'),
    require('../../../assets/black-stars/reactions/courier/13-furious-stomp.png'),
    require('../../../assets/black-stars/reactions/courier/14-backward-escape.png'),
    require('../../../assets/black-stars/reactions/courier/15-cheek-shield.png'),
    require('../../../assets/black-stars/reactions/courier/16-floor-cling.png'),
    require('../../../assets/black-stars/reactions/courier/17-starfish-tantrum.png'),
    require('../../../assets/black-stars/reactions/courier/18-offended-turnaway.png'),
    require('../../../assets/black-stars/reactions/courier/19-tiny-rage-shake.png'),
    require('../../../assets/black-stars/reactions/courier/20-ultimate-enough.png'),
  ],
  commander: [
    require('../../../assets/black-stars/reactions/commander/01-startled.png'),
    require('../../../assets/black-stars/reactions/commander/02-hold-cheek.png'),
    require('../../../assets/black-stars/reactions/commander/03-protest.png'),
    require('../../../assets/black-stars/reactions/commander/04-sulk.png'),
    require('../../../assets/black-stars/reactions/commander/05-notice.png'),
    require('../../../assets/black-stars/reactions/commander/06-evade.png'),
    require('../../../assets/black-stars/reactions/commander/07-parry.png'),
    require('../../../assets/black-stars/reactions/commander/08-signature-counter.png'),
    require('../../../assets/black-stars/reactions/commander/09-bawling-waterfall.png'),
    require('../../../assets/black-stars/reactions/commander/10-defensive-curl.png'),
    require('../../../assets/black-stars/reactions/commander/11-frantic-no.png'),
    require('../../../assets/black-stars/reactions/commander/12-dramatic-faint.png'),
    require('../../../assets/black-stars/reactions/commander/13-furious-stomp.png'),
    require('../../../assets/black-stars/reactions/commander/14-backward-escape.png'),
    require('../../../assets/black-stars/reactions/commander/15-cheek-shield.png'),
    require('../../../assets/black-stars/reactions/commander/16-floor-cling.png'),
    require('../../../assets/black-stars/reactions/commander/17-starfish-tantrum.png'),
    require('../../../assets/black-stars/reactions/commander/18-offended-turnaway.png'),
    require('../../../assets/black-stars/reactions/commander/19-tiny-rage-shake.png'),
    require('../../../assets/black-stars/reactions/commander/20-ultimate-enough.png'),
  ],
} as const satisfies Readonly<Record<EnemyId, BlackStarReactionAssetTuple>>;
