import type { EnemyId } from '@/data/enemies';

import type { BlackStarCharacterProfile } from './types';

/**
 * The serious names are deliberately played straight. Their contrast with the
 * incident stories supplies the comedy; the profiles themselves never wink at
 * the joke.
 */
export const BLACK_STAR_PROFILES = [
  {
    id: 'black-star:magician',
    kind: 'black-star',
    enemyId: 'magician',
    order: 1,
    name: '天城 幻十郎',
    reading: 'あまぎ げんじゅうろう',
    title: '奇術師',
    catchphrase: '虚実の境界を支配する奇術師',
    role: '偽物を本物以上の芸術へ変える、黒星の舞台演出者',
    personality: '完璧な段取りと劇的な美学を愛する自信家。仕掛けを見破られることより、演出を雑に扱われることを嫌う。',
    palette: { primary: '#171216', secondary: '#4A1725', accent: '#B93B55', surface: '#241A20', onSurface: '#F9E9ED' },
    image: require('../../../assets/enemies/magician.png'),
    tags: ['奇術', '虚実', '完璧主義', '舞台'],
    voice: {
      firstPerson: '私',
      style: '芝居がかった断定口調。余裕を崩さず、失敗さえ予定された演目として言い換える。',
      lines: {
        introduction: ['天城幻十郎。今から君が目にするものだけを、真実と呼べ。'],
        incident: ['幕は上がった。種明かしは、すべてが終わったあとだ。', '偶然ではない。君が驚く時刻まで計算してある。'],
        unlock: ['客席に置いておくには惜しい。次の演目から、君も共犯者だ。'],
        tease: ['私の帽子に触れるなら、消失する覚悟を決めておけ。', 'その程度で動揺するとでも？　……もう一度、同じ場所を狙え。'],
        care: ['静かな観客は嫌いではない。最後まで見届ける者なら、なおさらだ。'],
        gift: ['贈り物か。ならば次の舞台で、最も美しい形にして返そう。'],
      },
    },
    reactionArtDirection: {
      composure: '長いシルクハットのつばを直し、すべて予定どおりだと装う',
      signatureMotion: '深紅の裏地を翻して半歩引き、片目だけで相手を射抜く',
      breakingPoint: '帽子を押さえたまま外套が大きく開き、演出ではない焦りが初めて顔に出る',
      immutableDetails: ['黒い長身シルクハット', '深紅の帯と外套裏地', '銀の留め具と菱形チャーム'],
    },
  },
  {
    id: 'black-star:informant',
    kind: 'black-star',
    enemyId: 'informant',
    order: 2,
    name: '御影 静馬',
    reading: 'みかげ しずま',
    title: '情報屋',
    catchphrase: '沈黙まで記録する情報屋',
    role: '街の噂と秘密を結び、黒星へ最短の答えを届ける分析者',
    personality: '感情を情報として切り分ける冷静な観察者。知らないことを恐れないが、整理できない長話だけは密かに苦手。',
    palette: { primary: '#111719', secondary: '#0D4A4D', accent: '#38A6A3', surface: '#17282A', onSurface: '#E5FAF8' },
    image: require('../../../assets/enemies/informant.png'),
    tags: ['情報', '観察', '沈黙', '分析'],
    voice: {
      firstPerson: '私',
      style: '短く低い事務口調。事実、推測、結論を順に並べ、余計な感想を挟まない。',
      lines: {
        introduction: ['御影静馬。君が何を知りたいかは、質問される前から把握している。'],
        incident: ['事実は三つ。偶然はゼロ。結論だけ聞くか？', '声を落とせ。壁より先に、私が聞いている。'],
        unlock: ['記録対象から協力者へ変更する。異論は、データ付きで提出してくれ。'],
        tease: ['接触を確認。目的は不明。反復して傾向を採る。', '今の動作は記録した。……二度目も同じ強さで頼む。'],
        care: ['話さなくていい。沈黙にも十分な情報がある。'],
        gift: ['受領した。送り主の意図まで含め、厳重に保管する。'],
      },
    },
    reactionArtDirection: {
      composure: '帽子の影を深くして視線だけを動かし、状況を無言で記録する',
      signatureMotion: '青緑の外套を寄せ、封蝋付きの小さな封筒を守るように身を引く',
      breakingPoint: '情報量に処理が追いつかず、帽子がずれて目が大きく見開かれる',
      immutableDetails: ['黒いキャスケット', '青緑の外套裏地', '封蝋付き封筒のペンダント'],
    },
  },
  {
    id: 'black-star:tracker',
    kind: 'black-star',
    enemyId: 'tracker',
    order: 3,
    name: '狩谷 迅',
    reading: 'かりや じん',
    title: '追跡者',
    catchphrase: '消えた足跡を狩る追跡者',
    role: '重心、歩幅、空気の揺れから標的の先回りをする黒星の追跡者',
    personality: '目的へ一直線な寡黙の実務家。痕跡を読むことに絶対の自信を持ち、派手な陽動ほど冷静に無視する。',
    palette: { primary: '#121119', secondary: '#302153', accent: '#8667C6', surface: '#211B31', onSurface: '#F0EAFE' },
    image: require('../../../assets/enemies/tracker.png'),
    tags: ['追跡', '足跡', '寡黙', '先回り'],
    voice: {
      firstPerson: '俺',
      style: '単語を削った低い口調。観察した事実を言い切り、脅しや誇張を必要としない。',
      lines: {
        introduction: ['狩谷迅。逃げ道を選べ。どれを選んでも、先で待つ。'],
        incident: ['歩幅が乱れた。焦っているな。', '音を消しても重さは消えない。そこだ。'],
        unlock: ['もう追う必要はない。今度は同じ方向へ行く。'],
        tease: ['右から来ると読んでいた。……左は想定外だ。', '痕跡を残したな。次は触れる前に捕まえる。'],
        care: ['ここにいろ。見失わない距離が、一番安全だ。'],
        gift: ['軽い。だが、込められた意図は重い。受け取る。'],
      },
    },
    reactionArtDirection: {
      composure: '広いつばの帽子の奥から鋭く見据え、足元のわずかな痕跡へ意識を向ける',
      signatureMotion: '紫の縁取りを一直線に流し、外套を低く構えて瞬時に回避する',
      breakingPoint: '追跡方向を完全に外され、外套の裾を広げたまま両足で急停止する',
      immutableDetails: ['広いつばの黒帽子', '紫の細い縁取り', '鋭くつり上がった左目'],
    },
  },
  {
    id: 'black-star:safecracker',
    kind: 'black-star',
    enemyId: 'safecracker',
    order: 4,
    name: '久世 錠士郎',
    reading: 'くぜ じょうしろう',
    title: '金庫破り',
    catchphrase: '沈黙の錠前を聴く金庫破り',
    role: '機械式の錠前を音だけで解き、痕跡を残さず扉を開く黒星の職人',
    personality: '道具と手順を重んじる頑固な職人気質。集中を乱されると不機嫌になるが、美しい仕事や丁寧な作法には敬意を払う。',
    palette: { primary: '#151916', secondary: '#49331E', accent: '#BA8C49', surface: '#25221B', onSurface: '#FFF3DA' },
    image: require('../../../assets/enemies/safecracker.png'),
    tags: ['解錠', '職人', '聴覚', '精密'],
    voice: {
      firstPerson: '俺',
      style: 'ぶっきらぼうな職人口調。数字と手順には細かいが、認めた相手には短い賛辞を返す。',
      lines: {
        introduction: ['久世錠士郎。閉じたままでいられる扉など、まだ見たことがない。'],
        incident: ['静かにしろ。錠前が次の数字をしゃべっている。', '三秒で開ける。邪魔をするなら二秒で終わらせる。'],
        unlock: ['鍵は開いた。ここから先は、俺もそちら側だ。'],
        tease: ['指先が狂う。仕事中に触るな。……仕事外なら一度だけだ。', '今の衝撃で一段ずれた。責任を取って支えていろ。'],
        care: ['何も直さなくていい時間もある。今日はそのままでいろ。'],
        gift: ['悪くない作りだ。手入れして、一生使えるようにしてやる。'],
      },
    },
    reactionArtDirection: {
      composure: '山高帽の鍵飾りを確かめ、音を聞き分けるように片目を細める',
      signatureMotion: '真鍮の鍵束を鳴らさないよう押さえ、低い重心で踏ん張る',
      breakingPoint: '精密な集中が切れて鍵束が一斉に跳ね、帽子まで浮くほど驚く',
      immutableDetails: ['鍵飾り付きの山高帽', '真鍮色の鍵束', '深緑の外套裏地'],
    },
  },
  {
    id: 'black-star:veiled-duchess',
    kind: 'black-star',
    enemyId: 'veiled-duchess',
    order: 5,
    name: '黒姫 紫苑',
    reading: 'くろひめ しおん',
    title: '仮面の貴婦人',
    catchphrase: '名も顔も夜へ隠す仮面の貴婦人',
    role: '装いと声色を変え、標的の目前へ堂々と入り込む黒星の潜入者',
    personality: '気高さと威圧を崩さない完璧主義者。恐れられることを当然と考える一方、努力を見抜いて労われることには極端に弱い。',
    palette: { primary: '#18131A', secondary: '#4D1D45', accent: '#A95E9E', surface: '#2A1D2B', onSurface: '#F9EAF8' },
    image: require('../../../assets/enemies/veiled-duchess.png'),
    tags: ['変装', '潜入', '威厳', '仮面'],
    voice: {
      firstPerson: 'わたくし',
      style: '上品で冷たい貴族口調。命令さえ招待状のように言い渡し、驚くと一瞬だけ素の声になる。',
      lines: {
        introduction: ['黒姫紫苑。わたくしの素顔を知る必要も、資格もなくてよ。'],
        incident: ['扉をお開けなさい。招かれていないからこそ、参りましたの。', '恐怖は作法です。目を逸らさず、正しく怯えなさい。'],
        unlock: ['特別に、仮面の内側へ席を用意しましょう。光栄に思いなさい。'],
        tease: ['無礼ですわ。……その勇気だけは、もう一度見せてもよろしくてよ。', 'この羽飾りに触れた代償、高くつきましてよ。'],
        care: ['静かにお座りなさい。今宵だけは、何者にも演じなくて結構です。'],
        gift: ['趣味は悪くありませんわ。わたくしの宝石箱に加えて差し上げます。'],
      },
    },
    reactionArtDirection: {
      composure: '黒いヴェール越しに紫の左目を細め、宝石の留め具へ指先を添える',
      signatureMotion: '紫の外套裏地と羽飾りを優雅に流し、乱れても姿勢だけは崩さない',
      breakingPoint: 'ヴェールが跳ね上がり、貴婦人の威厳を忘れた大きな驚きが左目に表れる',
      immutableDetails: ['黒い網状ヴェール', '紫石と黒羽の帽子飾り', '銀細工の紫石ブローチ'],
    },
  },
  {
    id: 'black-star:courier',
    kind: 'black-star',
    enemyId: 'courier',
    order: 6,
    name: '速水 玲司',
    reading: 'はやみ れいじ',
    title: '運び屋',
    catchphrase: '約束の時刻を違えない運び屋',
    role: 'どんな荷物も一度で届け、経路と時刻を守り抜く黒星の運び屋',
    personality: '契約と時間に厳格で、最短経路を崩さない生真面目な実務家。想定外の受取人や再配達にだけ露骨に困惑する。',
    palette: { primary: '#171512', secondary: '#583318', accent: '#D9822B', surface: '#2A2118', onSurface: '#FFF0DC' },
    image: require('../../../assets/enemies/courier.png'),
    tags: ['配送', '契約', '時間厳守', '経路'],
    voice: {
      firstPerson: '私',
      style: '明瞭で規則正しい業務口調。時刻を秒まで読み上げ、受領確認が済むまで決して立ち去らない。',
      lines: {
        introduction: ['速水玲司。指定された場所へ、指定されたものを、指定時刻どおりに届ける。'],
        incident: ['経路変更は認めない。遅延理由は到着後に聞く。', '受領者を確認。ここへ署名を。話はそれからだ。'],
        unlock: ['配送は完了した。次の目的地は、君と決める。'],
        tease: ['予定外の接触だ。到着時刻を三秒修正する。', '妨害と判断する。……ただし悪意なし、処分は保留だ。'],
        care: ['急がなくていい。君の歩幅に合わせた経路へ変更済みだ。'],
        gift: ['確かに受領した。返礼は期日指定なしで届けよう。'],
      },
    },
    reactionArtDirection: {
      composure: '制帽の位置を正し、胸元の鍵と時刻を確かめて経路を再計算する',
      signatureMotion: '橙色の外套裏地を後方へ流し、荷崩れを防ぐよう両腕を固める',
      breakingPoint: '経路も受取人も想定から外れ、四角い左目を見開いてその場で急停止する',
      immutableDetails: ['金の翼章付き制帽', '橙色の外套裏地と縫い目', '胸元の金色の鍵'],
    },
  },
  {
    id: 'black-star:commander',
    kind: 'black-star',
    enemyId: 'commander',
    order: 7,
    name: '皇城 統雅',
    reading: 'すめらぎ とうが',
    title: '司令官',
    catchphrase: '敗北を計画から排除する司令官',
    role: '六人の技能を一つの作戦へ束ね、黒星の全行動を指揮する司令官',
    personality: '目的達成のためなら膨大な検証を厭わない統率者。規律に厳しいが部下の失敗を見捨てず、最後は自分の責任として報告書へ記す。',
    palette: { primary: '#171313', secondary: '#4D181B', accent: '#C49B53', surface: '#2A1D1D', onSurface: '#FFF0E4' },
    image: require('../../../assets/enemies/commander.png'),
    tags: ['指揮', '作戦', '規律', '責任'],
    voice: {
      firstPerson: '私',
      style: '揺るぎない命令口調。状況を番号で整理し、どれほど混乱しても最後まで作戦名を正式名称で呼ぶ。',
      lines: {
        introduction: ['皇城統雅。黒星総員の行動は、これより私の指揮下に置く。'],
        incident: ['第一案を破棄。第二案へ移行する。動揺は作戦終了後に許可する。', '失敗ではない。未検証の条件が一つ増えただけだ。'],
        unlock: ['本作戦を完了とする。以後、君を黒星の正式な同行者として扱う。'],
        tease: ['私を試す行為は計画にない。……検証項目として一度だけ認める。', '姿勢を崩すな。触れた側にも規律は適用される。'],
        care: ['休息も命令だ。今日は私が周囲を警戒する。'],
        gift: ['受領した。私物としてではなく、信頼の証として携行する。'],
      },
    },
    reactionArtDirection: {
      composure: '金縁の制帽と外套を正し、動揺を押し込めて次の命令を組み立てる',
      signatureMotion: '赤い外套裏地を大きく開き、片腕を上げて場を制止しようとする',
      breakingPoint: '完璧な作戦が崩れ、制帽が傾いたまま命令する言葉を失って立ち尽くす',
      immutableDetails: ['赤い細線と黒い宝石の制帽章', '金縁の黒い外套', '赤石と星章の装飾'],
    },
  },
] as const satisfies readonly BlackStarCharacterProfile[];

export const BLACK_STAR_PROFILE_BY_ENEMY_ID = Object.fromEntries(
  BLACK_STAR_PROFILES.map((profile) => [profile.enemyId, profile]),
) as unknown as Readonly<Record<EnemyId, BlackStarCharacterProfile>>;

export function getBlackStarProfile(enemyId: EnemyId): BlackStarCharacterProfile {
  return BLACK_STAR_PROFILE_BY_ENEMY_ID[enemyId];
}
