import { Platform, StyleSheet } from 'react-native';

const COLLECTION_BOARD_TOP = 128;

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#E7D3BC' },
  outer: { flex: 1, width: '100%', height: '100%', alignItems: 'center', justifyContent: 'flex-start', backgroundColor: Platform.OS === 'web' ? '#E7D3BC' : '#FFF7EA' },
  appViewport: { flex: 1, width: '100%', position: 'relative', overflow: 'hidden', backgroundColor: '#E7D3BC', ...(Platform.OS === 'web' ? { boxShadow: '0 16px 48px rgba(81, 48, 54, 0.18)' } : {}) },
  appShell: { flex: 1, width: '100%', maxWidth: 720, alignSelf: 'center', backgroundColor: '#D8A46F', overflow: Platform.OS === 'web' ? ('clip' as any) : 'hidden' },
  appBaseLayer: { flex: 1, position: 'relative' },
  globalHeaderPlaceholder: { minHeight: 74 },
  appShellBackground: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  collectionReferenceBackground: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  loadingOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 140, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(76,53,71,0.36)' },
  loadingCard: { width: 286, minHeight: 290, paddingHorizontal: 24, paddingTop: 15, paddingBottom: 22, borderRadius: 32, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  loadingCardImage: { ...StyleSheet.absoluteFillObject },
  loadingMascotWrap: { width: 210, height: 198, alignItems: 'center', justifyContent: 'flex-end' },
  loadingMascotWrapCompact: { width: 90, height: 62, marginBottom: -9 },
  loadingMascotImage: { width: 185, height: 175 },
  loadingMascotImageCompact: { width: 68, height: 58 },
  loadingDots: { height: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  loadingDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#735574' },
  loadingTitle: { color: '#5D405B', fontSize: 18, lineHeight: 23, fontWeight: '900', marginTop: 2 },
  loadingText: { color: '#98737E', fontSize: 12, lineHeight: 15, fontWeight: '800', marginTop: 4 },
  pressableFocusReset: { outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  panelStretchImage: { width: '100%', height: '100%' },
  onboardingOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 115, alignItems: 'center', justifyContent: 'center' },
  onboardingBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(67,44,61,0.025)' },
  favoriteCard: { position: 'absolute', top: 32, left: 14, right: 14, bottom: 24, paddingHorizontal: 16, paddingTop: 18, paddingBottom: 16, borderRadius: 30, overflow: 'hidden', alignItems: 'center' },
  favoriteCardImage: { ...StyleSheet.absoluteFillObject },
  favoriteGlassSheen: { position: 'absolute', top: 9, left: 18, right: 18, height: 86, borderRadius: 28, backgroundColor: 'rgba(255,255,255,0.035)', borderTopWidth: 1.4, borderColor: 'rgba(255,255,255,0.3)' },
  favoriteTitle: { color: '#553B59', fontSize: 23, lineHeight: 29, fontWeight: '900', marginTop: 4 },
  favoriteLead: { width: 320, color: '#8D6C76', fontSize: 16, lineHeight: 23, fontWeight: '800', textAlign: 'center', marginTop: 4, marginBottom: 10 },
  favoriteCarousel: { width: '100%', minHeight: 366, marginTop: -2 },
  onboardingPrimaryButton: { width: '100%', minHeight: 48, marginTop: 10, overflow: 'hidden' },
  onboardingPrimaryContent: { minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  onboardingPrimaryButtonPressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
  onboardingPrimaryText: { color: '#FFF9EC', fontSize: 16, lineHeight: 22, fontWeight: '900', letterSpacing: 0.4 },
  guideOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 100 },
  guideNavHighlight: { position: 'absolute', bottom: Platform.OS === 'web' ? 17 : 10, height: 60, padding: 3, borderRadius: 20, borderWidth: 2, borderColor: '#C9778B', backgroundColor: 'rgba(255,240,225,0.18)', zIndex: 104, shadowColor: '#6A4158', shadowOpacity: 0.25, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 10 },
  guideNavHighlightInner: { flex: 1, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(255,247,228,0.92)' },
  guideCard: { position: 'absolute', left: 10, right: 10, paddingHorizontal: 28, paddingTop: 23, paddingBottom: 25, shadowColor: '#4E3449', shadowOpacity: 0.23, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 11 },
  guideCardImage: { width: '100%', height: '100%' },
  guideCardBottom: { bottom: 84, minHeight: 210 },
  guideCardTop: { top: 78, minHeight: 176 },
  guideHeadingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  guideStep: { color: '#A3727E', fontSize: 13, lineHeight: 18, fontWeight: '900', letterSpacing: 1.1 },
  guideSkip: { color: '#91717B', fontSize: 13, lineHeight: 18, fontWeight: '900', textDecorationLine: 'underline' },
  guideTitle: { color: '#5C405B', fontSize: 19, lineHeight: 26, fontWeight: '900', marginTop: 5 },
  guideBody: { color: '#876872', fontSize: 16, lineHeight: 24, fontWeight: '800', marginTop: 5 },
  guideButton: { alignSelf: 'flex-end', width: 142, height: 46, marginTop: 10, overflow: 'hidden' },
  guideButtonInner: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center' },
  guideButtonContent: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center' },
  guideButtonText: { color: '#FFF9EC', fontSize: 16, lineHeight: 22, fontWeight: '900' },
  openingScreen: { ...StyleSheet.absoluteFillObject, zIndex: 100, overflow: 'hidden' },
  openingBackdrop: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  openingTapSurface: { ...StyleSheet.absoluteFillObject, zIndex: 6, backgroundColor: 'transparent' },
  openingTitleWrap: { position: 'absolute', top: 34, left: 24, right: 24, alignItems: 'center', zIndex: 8 },
  openingTitlePlaque: { width: 310, height: 129, alignItems: 'center', justifyContent: 'center', paddingTop: 4 },
  openingLogoImage: { width: 280, height: 99 },
  openingScene: { position: 'absolute', top: 0, left: 0, right: 0, height: 428 },
  openingOpenedBox: { position: 'absolute', top: 0, left: '50%', width: 360, height: 360, marginLeft: -180, zIndex: 1 },
  openingKeyDecoration: { position: 'absolute' },
  openingMobby: { position: 'absolute', top: 69, left: '50%', width: 222, height: 252, marginLeft: -111, zIndex: 3 },
  openingUnopenedPackage: { position: 'absolute', left: '50%', zIndex: 4 },
  openingStartWrap: { position: 'absolute', left: 18, right: 18, bottom: 18, alignItems: 'center', zIndex: 9 },
  openingStartButton: { width: 292, height: 126, alignItems: 'center', justifyContent: 'center', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  openingStartLoading: { opacity: 0.78 },
  openingStartPressed: { transform: [{ scale: 0.96 }] },
  openingStartPlaque: { width: 292, height: 126, alignItems: 'center', justifyContent: 'center', paddingTop: 4 },
  openingStartTitle: { color: '#64425D', fontSize: 16, fontWeight: '900', letterSpacing: 1.7 },
  openingStartSub: { color: '#9A707C', fontSize: 12, fontWeight: '900', marginTop: 3 },
  header: { minHeight: 74, paddingHorizontal: 16, paddingTop: 7, paddingBottom: 8, flexDirection: 'row', alignItems: 'center', backgroundColor: 'transparent', borderBottomWidth: 0 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  soundButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  soundButtonText: { color: '#76536F', fontSize: 19, lineHeight: 21, fontWeight: '900' },
  settingsIcon: { width: 23, height: 23 },
  headerSettingsIcon: { width: 23, height: 23 },
  bellButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  bellIcon: { width: 21, height: 21 },
  bellBadge: { position: 'absolute', right: -4, top: -6, width: 17, height: 17, borderRadius: 9, backgroundColor: '#E47884', borderWidth: 1.5, borderColor: '#FFF8EC', alignItems: 'center', justifyContent: 'center' },
  bellBadgeText: { color: '#FFF', fontSize: 12, fontWeight: '900' },
  noticeToast: { position: 'absolute', zIndex: 30, top: 78, left: 15, right: 15, minHeight: 44, overflow: 'hidden' },
  noticeToastImage: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  noticeToastContent: { minHeight: 44, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center' },
  noticeToastText: { flex: 1, color: '#FFF8ED', fontSize: 12, fontWeight: '800' },
  noticeToastClose: { color: '#F5CED2', fontSize: 21, marginLeft: 8 },
  screenBody: { flex: 1 },
  timeScrollContent: { paddingHorizontal: 14, paddingTop: 0, alignItems: 'center' },
  homeScreenBackground: { flex: 1 },
  brandWrap: { width: 124, height: 48, alignItems: 'flex-start', justifyContent: 'center' },
  headerLogoImage: { width: 120, height: 47 },
  headerDressUpButton: { width: 112, height: 48, overflow: 'hidden' },
  headerDressUpContent: { width: 112, height: 48, paddingHorizontal: 9, alignItems: 'center', justifyContent: 'center' },
  headerDressUpText: { color: '#6B4A62', fontSize: 13, lineHeight: 17, fontWeight: '900' },
  headerSpacer: { flex: 1 },
  homeRoom: { flex: 1, position: 'relative', overflow: 'hidden' },
  homeArrangeBackgroundTarget: { ...StyleSheet.absoluteFillObject, zIndex: 1 },
  homeReorderButton: { position: 'absolute', top: 4, right: 14, zIndex: 28, minWidth: 88, minHeight: 44, overflow: 'hidden' },
  homeReorderButtonContent: { minWidth: 88, minHeight: 44, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center' },
  homeReorderButtonActive: {},
  homeReorderButtonText: { color: '#6B4A62', fontSize: 13, fontWeight: '900', letterSpacing: 0.5 },
  homeReorderButtonTextActive: { color: '#6B4A62' },
  homeReorderSelected: { backgroundColor: 'rgba(255,238,166,0.5)', borderWidth: 3, borderColor: '#8B607A' },
  homeShelfBase: { position: 'absolute', top: '-15%', left: 0, right: 0, width: '100%', height: '100%', zIndex: 0 },
  homeGarland: { position: 'absolute', top: -27, left: 5, width: 430, height: 138, zIndex: 1, opacity: 0.86 },
  homeDecorAsset: { width: '100%', height: '100%' },
  // Ten wall slots are distributed over two broad rows so the center stage
  // remains clear for the selected Mobby and the shelf below.
  homeWallKeys: { position: 'absolute', top: '7%', left: '7%', right: '7%', height: '43%', flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-start', alignContent: 'flex-start', zIndex: 2 },
  homeWallSlot: { width: '20%', height: '43%', position: 'relative', overflow: 'visible', borderRadius: 12 },
  homeWallKey: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'flex-start', borderRadius: 12, position: 'relative', overflow: 'visible', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  homeWallKeyHidden: { opacity: 0 },
  homeWallKeyStolen: { zIndex: 18 },
  homeWallKeyReturning: { zIndex: 12 },
  homeWallReturningImage: { opacity: 0.74 },
  homeWallStolenMarker: { position: 'absolute', top: -16, left: -10, right: -10, height: 152, borderRadius: 22, borderWidth: 3, alignItems: 'center', justifyContent: 'center', shadowColor: '#F32D48', shadowOpacity: 0.8, shadowRadius: 14, shadowOffset: { width: 0, height: 0 }, elevation: 16 },
  homeWallStolenGhost: { position: 'absolute', top: 22, width: 92, height: 102, opacity: 0.2, tintColor: '#441723' },
  homeWallStolenGhostSmall: { width: 74, height: 84, top: 28 },
  homeWallCaseTag: { position: 'absolute', top: 4, left: 4, paddingHorizontal: 6, paddingVertical: 3, borderRadius: 6, backgroundColor: '#27131D', borderWidth: 1, borderColor: '#FF8994' },
  homeWallCaseTagText: { color: '#FFE6D7', fontSize: 12, fontWeight: '900', letterSpacing: 0.6 },
  homeWallStolenBand: { position: 'absolute', left: -8, right: -8, top: 54, height: 35, backgroundColor: '#B8273E', borderTopWidth: 2, borderBottomWidth: 2, borderColor: '#FFD0B8', alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-8deg' }] },
  homeWallStolenBandText: { color: '#FFF9E8', fontSize: 14, fontWeight: '900', letterSpacing: 1.2 },
  homeWallStolenName: { position: 'absolute', left: 2, right: 2, bottom: 23, color: '#FFF1DE', fontSize: 12, fontWeight: '900', textAlign: 'center', textShadowColor: '#35101B', textShadowRadius: 3 },
  homeWallResume: { position: 'absolute', bottom: 4, color: '#FFCFB6', fontSize: 12, fontWeight: '900', letterSpacing: 0.1 },
  homeWallHook: { position: 'absolute', top: -25, left: '50%', width: 54, height: 81, marginLeft: -27, zIndex: 0 },
  homeWallKeySwing: { alignItems: 'center', transformOrigin: '50% 0%', marginTop: 11 },
  // The hook plate's round center is the hanging point. Start each keychain
  // there so the chain visibly comes out of the center of the wood hook.
  homeWallKeyImage: { width: 96, height: 106 },
  homeWallSmallKeyImage: { width: 76, height: 84 },
  // The wall image has its first wooden shelf directly below the key pegs.
  // Keep the plush feet on that shelf board instead of letting them fall onto
  // the rug at the bottom of the room.
  // The base image's visible top surface sits just below its alpha edge;
  // this fractional offset puts the visible foot soles on that surface.
  // The transparent base's top surface sits just below the artwork's visual
  // center.  Keep the plush row a little lower so each visible foot meets the
  // wood instead of floating above it (the source images contain transparent
  // padding below the feet).
  homePlushShelf: { position: 'absolute', left: '8%', right: '8%', height: '18%', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', zIndex: 3 },
  homePlushSlot: { width: '25%', height: '100%', position: 'relative', overflow: 'visible', borderRadius: 13 },
  homePlushItem: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'flex-end', borderRadius: 13, position: 'relative', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  homePlushSwing: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'flex-end', transformOrigin: '50% 100%' },
  homePlushImage: { width: 70, height: 80 },
  homeArrangeDraggable: { flex: 1, width: '100%', height: '100%', position: 'relative', overflow: 'visible' },
  homeArrangeContent: { flex: 1, width: '100%', height: '100%' },
  homeArrangePlacementVisual: { flex: 1, width: '100%', height: '100%' },
  homeArrangeDraggedItem: { opacity: 0 },
  homeArrangeGestureSurface: { ...StyleSheet.absoluteFillObject, zIndex: 40, backgroundColor: 'rgba(255,255,255,0.001)' },
  homeArrangeDragging: { zIndex: 48, shadowColor: '#493141', shadowOpacity: 0.35, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 18 },
  homeArrangeSourceSlot: { zIndex: 52, elevation: 20 },
  homeArrangeSlot: { borderWidth: 1, borderColor: 'rgba(118,75,100,0.12)', borderStyle: 'dashed' },
  homeArrangeActiveSlot: { zIndex: 46 },
  homeArrangeDropTarget: { backgroundColor: 'rgba(255,241,164,0.62)', borderWidth: 3, borderColor: '#D66E7C', shadowColor: '#FFF1A8', shadowOpacity: 0.86, shadowRadius: 10, shadowOffset: { width: 0, height: 0 }, elevation: 9 },
  homeArrangeEmptySlot: { flex: 1, margin: 5, borderRadius: 12, borderWidth: 2, borderStyle: 'dashed', borderColor: 'rgba(125,79,104,0.46)', backgroundColor: 'rgba(255,250,232,0.2)', alignItems: 'center', justifyContent: 'center' },
  homeArrangeEmptyPlus: { color: 'rgba(112,70,95,0.7)', fontSize: 22, lineHeight: 25, fontWeight: '900' },
  homeArrangeRemoveButton: { position: 'absolute', top: -8, left: -7, width: 25, height: 25, borderRadius: 13, zIndex: 60, backgroundColor: '#C95568', borderWidth: 2, borderColor: '#FFF8EA', alignItems: 'center', justifyContent: 'center', shadowColor: '#583044', shadowOpacity: 0.28, shadowRadius: 4, shadowOffset: { width: 0, height: 2 }, elevation: 8 },
  homeArrangeRemoveText: { color: '#FFF', fontSize: 19, lineHeight: 20, fontWeight: '900', marginTop: -2 },
  homeArrangeMainDimmed: { opacity: 0.2 },
  homeInventoryTray: { position: 'absolute', left: 8, right: 8, bottom: 72, zIndex: 62 },
  homeArrangeHint: { position: 'absolute', left: 52, right: 52, bottom: 258, minHeight: 30, zIndex: 63, borderRadius: 15, paddingHorizontal: 12, paddingVertical: 6, backgroundColor: 'rgba(87,57,77,0.88)', alignItems: 'center', justifyContent: 'center' },
  homeArrangeHintText: { color: '#FFF9E9', fontSize: 10, lineHeight: 13, fontWeight: '900', textAlign: 'center' },
  homeArrangeDragOverlay: { position: 'absolute', zIndex: 96, alignItems: 'center', justifyContent: 'center', shadowColor: '#493141', shadowOpacity: 0.42, shadowRadius: 14, shadowOffset: { width: 0, height: 9 }, elevation: 24, transform: [{ scale: 1.1 }] },
  homeArrangeDragOverlayImage: { width: '100%', height: '100%' },
  homeSelectablePressed: { opacity: 0.74, transform: [{ scale: 0.96 }] },
  homeMainCharacter: { position: 'absolute', left: '50%', bottom: 90, width: 220, height: 250, marginLeft: -110, zIndex: 8 },
  homeMainCharacterCompact: { bottom: 60, width: 178, height: 198, marginLeft: -89 },
  homeMainCharacterPullable: { alignItems: 'center', justifyContent: 'flex-end', overflow: 'visible' },
  reactionBookButton: { position: 'absolute', right: -80, top: '41%', minWidth: 92, minHeight: 62, zIndex: 24 },
  reactionBookButtonCompact: { right: -75, top: '41%', minWidth: 82, minHeight: 56 },
  reactionBookButtonContent: { minHeight: 56, paddingHorizontal: 8, paddingVertical: 8, alignItems: 'center', justifyContent: 'center' },
  reactionBookButtonLabel: { color: '#6B4A62', fontSize: 11, lineHeight: 14, fontWeight: '900', textAlign: 'center' },
  homeReactionBubble: { position: 'absolute', right: 10, width: 140, height: 72, paddingHorizontal: 12, paddingVertical: 8, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', transform: [{ rotate: '-2deg' }], zIndex: 12 },
  homeReactionBubbleImage: { width: '100%', height: '100%' },
  homeReactionBubbleText: { color: '#5E4057', fontSize: 12, lineHeight: 14, fontWeight: '900', textAlign: 'center' },
  collectionHeaderBar: { position: 'absolute', top: 8, left: 18, right: 18, height: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', zIndex: 10, overflow: 'hidden' },
  collectionScreenBackground: { flex: 1, backgroundColor: 'transparent' },
  collectionScrollContent: { flex: 1, position: 'relative' },
  collectionStage: { position: 'relative', width: 440, alignSelf: 'center', overflow: 'visible' },
  collectionBoardShadow: { position: 'absolute', top: 134, left: 30, width: 380, borderRadius: 36, backgroundColor: 'rgba(72,44,31,0.24)', shadowColor: '#3D281F', shadowOpacity: 0.42, shadowRadius: 22, shadowOffset: { width: 0, height: 10 }, elevation: 11, zIndex: 1 },
  collectionDisplayBoard: { position: 'absolute', top: COLLECTION_BOARD_TOP, left: 25, width: 390, borderRadius: 36, overflow: 'hidden', zIndex: 2 },
  collectionHeaderCopy: { width: 145, height: 48, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, paddingBottom: 1, overflow: 'hidden' },
  collectionHeaderTitle: { color: '#563C50', fontSize: 14, lineHeight: 18, fontWeight: '900', letterSpacing: 0.2, fontFamily: 'MochiyPopOne_400Regular' },
  collectionModeTabs: { width: 180, height: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 7, paddingVertical: 5, overflow: 'hidden' },
  collectionModeTab: { position: 'relative', minWidth: 78, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  collectionModeTabContent: { minWidth: 74, minHeight: 44, paddingHorizontal: 10, alignItems: 'center', justifyContent: 'center' },
  collectionModeText: { color: '#876C7D', fontSize: 12, fontWeight: '800' },
  collectionModeTextActive: { color: '#65475E' },
  collectionKeySizeTabs: { position: 'absolute', top: 66, left: '50%', marginLeft: -92, width: 184, height: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 9, gap: 3, overflow: 'hidden', zIndex: 10 },
  collectionKeySizeLabel: { color: '#8B6B79', fontSize: 12, fontWeight: '800', marginRight: 2 },
  collectionKeySizeTab: { position: 'relative', width: 54, height: 44, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  collectionKeySizeTabPressed: { opacity: 0.72 },
  collectionKeySizeTabUnderline: { position: 'absolute', bottom: 4, width: 26, height: 2, borderRadius: 1, backgroundColor: '#65475E' },
  collectionKeySizeText: { color: '#967584', fontSize: 12, fontWeight: '800' },
  collectionKeySizeTextActive: { color: '#65475E' },
  collectionDisplay: { position: 'absolute', top: 0, left: 0, right: 0, backgroundColor: 'transparent', overflow: 'visible', zIndex: 3 },
  collectionDisplayPlush: { backgroundColor: 'transparent' },
  keyCollectionGrid: { ...StyleSheet.absoluteFillObject },
  collectionKeyItem: { width: 104, alignItems: 'center' },
  collectionKeyItemAnchored: { position: 'absolute' },
  collectionKeyPressable: { alignItems: 'center', outlineColor: 'transparent', outlineWidth: 0 },
  collectionKeySwing: { alignItems: 'center', transformOrigin: '50% 0%' },
  collectionKeyHookOwned: { height: 0 },
  collectionKeyHookPlaceholder: { position: 'absolute', top: -54, width: 55, height: 83, opacity: 0.62 },
  collectionKeyBody: { width: 55, height: 70, alignItems: 'center', justifyContent: 'center', overflow: 'visible' },
  collectionKeyBodyOwned: { width: 104, height: 122, borderRadius: 0, borderWidth: 0, borderColor: 'transparent', backgroundColor: 'transparent', overflow: 'visible' },
  collectionKeySelected: { transform: [{ scale: 1.06 }] },
  collectionKeyImage: { width: 104, height: 122 },
  collectionSmallKeyImage: { width: 81, height: 95 },
  collectionKeyName: { position: 'absolute', top: -18, zIndex: 3, width: 104, color: '#503645', fontSize: 12, fontWeight: '700', textAlign: 'center', textShadowColor: '#FFF4DC', textShadowRadius: 2 },
  collectionKeyPlaceholderText: { color: 'rgba(118,95,107,0.66)', fontSize: 22, lineHeight: 26, fontWeight: '500' },
  plushCollectionShelf: { ...StyleSheet.absoluteFillObject },
  plushCollectionItem: { position: 'absolute', width: 110, height: 134, alignItems: 'center' },
  plushCollectionBody: { width: 110, height: 120, alignItems: 'center', justifyContent: 'flex-end', overflow: 'visible' },
  plushCollectionBodyOwned: { width: 110, height: 120, borderRadius: 0, borderWidth: 0, borderColor: 'transparent', backgroundColor: 'transparent', overflow: 'visible' },
  plushCollectionSelected: { transform: [{ scale: 1.05 }] },
  plushCollectionImage: { position: 'absolute', width: 110, height: 120 },
  plushCollectionPlaceholderText: { color: 'rgba(118,95,107,0.58)', fontSize: 25, lineHeight: 30, fontWeight: '500', marginBottom: 30 },
  collectionPlushName: { width: 110, color: '#503645', fontSize: 12, fontWeight: '700', textAlign: 'center', textShadowColor: '#FFF4DC', textShadowRadius: 2, marginTop: 1 },
  sectionTitle: { color: '#4C3451', fontSize: 19, fontWeight: '900', marginTop: 2 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  timeHeader: { alignSelf: 'stretch', height: 110, alignItems: 'center', paddingTop: 1, paddingHorizontal: 18 },
  timeHeaderPopover: { height: 86, paddingTop: 1 },
  timeTitle: { color: '#4B304B', fontSize: 22, lineHeight: 25, fontWeight: '900', letterSpacing: 0.4, textAlign: 'center', fontFamily: Platform.select({ ios: 'Hiragino Maru Gothic ProN', default: undefined }) },
  bigTitle: { color: '#4D3455', fontSize: 29, fontWeight: '900', letterSpacing: 1.2, marginTop: 3 },
  timeHeaderSub: { color: '#5D4051', fontSize: 12, lineHeight: 13, fontWeight: '700', marginTop: 0, textAlign: 'center', textShadowColor: '#FFF6E7', textShadowRadius: 4 },
  bigTimer: { marginTop: -2, width: 184, height: 66, alignItems: 'center', justifyContent: 'center', paddingTop: 2 },
  bigTimerLabel: { color: '#694A5C', fontSize: 12, lineHeight: 9, fontWeight: '900' },
  bigTimerValue: { color: '#422A43', fontSize: 24, lineHeight: 26, fontWeight: '900', letterSpacing: 1.4 },
  encounterCard: { alignSelf: 'center', paddingTop: 47, paddingHorizontal: 39, paddingBottom: 18 },
  encounterCardImage: { borderRadius: 24 },
  arrivalNotice: { minHeight: 35, marginBottom: 0, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  arrivalNoticeText: { color: '#4E3348', fontSize: 14, lineHeight: 20, fontWeight: '900', textAlign: 'center', textShadowColor: '#FFF4DE', textShadowRadius: 3 },
  encounterScene: { height: 306, borderRadius: 26, overflow: 'visible', alignItems: 'center', justifyContent: 'center', position: 'relative' },
  openingLightLayer: { ...StyleSheet.absoluteFillObject, zIndex: 1, alignItems: 'center', justifyContent: 'center', overflow: 'visible' },
  openingLightBeam: { position: 'absolute', top: 12, width: 154, height: 258, backgroundColor: 'rgba(255,244,176,0.68)', shadowColor: '#FFF6B5', shadowOpacity: 0.96, shadowRadius: 34, shadowOffset: { width: 0, height: 0 }, transformOrigin: 'center' },
  openingLightRay: { position: 'absolute', top: 24, width: 19, height: 238, backgroundColor: 'rgba(255,250,211,0.78)', shadowColor: '#FFFBDA', shadowOpacity: 0.92, shadowRadius: 20, shadowOffset: { width: 0, height: 0 }, transformOrigin: 'center' },
  openingLightRayLeft: { left: '50%', marginLeft: -130 },
  openingLightRayRight: { left: '50%', marginLeft: 111 },
  packageAnimationWrap: { ...StyleSheet.absoluteFillObject, zIndex: 3, alignItems: 'center', justifyContent: 'center', paddingTop: 22 },
  revealPackageTouch: { width: 242, height: 242, alignItems: 'center', justifyContent: 'center', position: 'relative', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  mobbyTimePackageAsset: { width: 224, height: 224 },
  packagePressed: { transform: [{ rotate: '1deg' }, { scale: 0.96 }] },
  packageCaptionSpacer: { height: 15 },
  magicParticles: { ...StyleSheet.absoluteFillObject, zIndex: 4, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingHorizontal: 28 },
  magicParticle: { color: '#FFF7B8', fontSize: 32, fontWeight: '900', textShadowColor: '#D98FA0', textShadowRadius: 8 },
  encounterRewardWrap: { width: 286, height: 312, alignItems: 'center', justifyContent: 'center', zIndex: 3 },
  encounterKeyImage: { width: 286, height: 312 },
  encounterSmallKeyImage: { width: 222, height: 244 },
  encounterPlushImage: { width: 222, height: 246 },
  placementSparkles: { ...StyleSheet.absoluteFillObject, zIndex: 5, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingHorizontal: 18 },
  placementSparkle: { color: '#FFF4A8', fontSize: 27, fontWeight: '900', textShadowColor: '#C96F8B', textShadowRadius: 7 },
  newBadge: { position: 'absolute', left: 7, bottom: 4, width: 72, height: 72, alignItems: 'center', justifyContent: 'center', paddingBottom: 12, transform: [{ rotate: '-7deg' }], zIndex: 5 },
  newBadgeText: { color: '#FFF8ED', fontSize: 12, fontWeight: '900', letterSpacing: 0.6, textShadowColor: 'rgba(91,58,76,0.34)', textShadowRadius: 2 },
  encounterBubble: { position: 'absolute', top: -8, right: -18, width: 176, height: 96, paddingHorizontal: 27, paddingTop: 17, paddingBottom: 20, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '3deg' }], zIndex: 6 },
  encounterBubbleTitle: { color: '#4E3048', fontSize: 16, lineHeight: 21, fontWeight: '900', textAlign: 'center', textShadowColor: '#FFF7E7', textShadowRadius: 2 },
  encounterBubbleText: { color: '#694B5A', fontSize: 13, lineHeight: 17, fontWeight: '800', marginTop: 1, textAlign: 'center' },
  encounterOpenButton: { alignSelf: 'center', width: 260, height: 52, overflow: 'hidden', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  encounterOpenButtonAsset: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center', paddingLeft: 20, paddingRight: 48, paddingBottom: 1 },
  encounterOpenButtonText: { color: '#FFF9ED', fontFamily: 'MochiyPopOne_400Regular', fontSize: 16, lineHeight: 22, fontWeight: '900', letterSpacing: 0.15, textAlign: 'center', textShadowColor: 'rgba(92,45,54,0.42)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 2 },
  encounterOpenButtonPressed: { opacity: 0.9, transform: [{ translateY: 2 }, { scale: 0.97 }] },
  encounterOpenButtonDisabled: { opacity: 0.58 },
  primaryButtonIcon: { width: 22, height: 22, marginRight: 5 },
  primaryButtonText: { color: '#FFF9EC', fontSize: 13, fontWeight: '900' },
  timePrimaryButton: { position: 'absolute', left: 63, bottom: 38, width: 244, height: 46, zIndex: 8, overflow: 'hidden', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  timePrimaryButtonInactive: { opacity: 0.58 },
  timePrimaryButtonText: { color: '#5B3D54', textShadowColor: 'rgba(255,251,232,0.62)', textShadowRadius: 2 },
  assetButtonInner: { width: '100%', height: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, paddingVertical: 8, overflow: 'hidden' },
  touchTop: { paddingTop: 7, paddingBottom: 12 },
  touchTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  rarityBadge: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10, marginLeft: 6 },
  rarityBadgeText: { color: '#FFF', fontSize: 12, fontWeight: '900' },
  touchScreenBackground: { flex: 1, backgroundColor: 'transparent' },
  touchScrollContent: { flex: 1, paddingHorizontal: 10, paddingTop: 10, paddingBottom: 82 },
  touchStage: { height: 500, borderRadius: 28, overflow: 'hidden', alignItems: 'center', justifyContent: 'center', position: 'relative' },
  pullableWrap: { width: 332, height: 365, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  pullableStage: { width: 320, height: 320, position: 'relative' },
  // PanResponder turns this view into an accessible button on web. Suppress
  // the browser's default focus ring so a completed pull does not leave a
  // harsh black rectangle over the parchment stage.
  // Match mobby-main's touch surface: prevent browser scrolling/selection
  // from cancelling a long cheek drag before pointerup.
  pullableSlot: { ...StyleSheet.absoluteFillObject, width: 320, height: 320, alignItems: 'center', justifyContent: 'center', zIndex: 2, outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent', touchAction: 'none', userSelect: 'none' },
  pullableBody: { width: 320, height: 320 },
  pullableFixedLayer: { ...StyleSheet.absoluteFillObject, zIndex: 3 },
  pullableFaceLayer: { zIndex: 4 },
  pullableReactionLayer: { ...StyleSheet.absoluteFillObject, zIndex: 5 },
  pullableReactionFrame: { ...StyleSheet.absoluteFillObject },
  pullableReactionBurst: { position: 'absolute', zIndex: 4, left: '18%', top: '18%', width: '64%', height: '64%', borderRadius: 999, borderWidth: 4, borderColor: 'rgba(255, 225, 151, 0.8)' },
  characterPickerButton: { position: 'absolute', zIndex: 20, width: 68, height: 51, overflow: 'hidden' },
  characterPickerButtonAsset: { width: '100%', height: '100%', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4, paddingVertical: 2, gap: 0 },
  characterPickerButtonLarge: { left: -68, top: '43%' },
  characterPickerButtonCompact: { left: -68, top: '41%' },
  characterPickerButtonPressed: { transform: [{ scale: 0.94 }], opacity: 0.88 },
  characterPickerCaption: { color: '#8B6D91', fontSize: 12, fontWeight: '800', lineHeight: 11 },
  characterPickerValue: { color: '#68465F', fontSize: 12, fontWeight: '900', lineHeight: 15 },
  animeEffectLayer: { ...StyleSheet.absoluteFillObject, zIndex: 6 },
  animeBurstRayWrap: { ...StyleSheet.absoluteFillObject },
  animeBurstRay: { position: 'absolute', width: 3, borderRadius: 3, backgroundColor: 'rgba(255, 225, 151, 0.88)' },
  animeCheekTrail: { position: 'absolute', top: '39%', gap: 6 },
  animeCheekTrailLeft: { left: '2%', alignItems: 'flex-start', transform: [{ rotate: '-8deg' }] },
  animeCheekTrailRight: { right: '2%', alignItems: 'flex-end', transform: [{ rotate: '8deg' }] },
  animeCheekStroke: { height: 3, borderRadius: 3, borderWidth: 0.7, borderColor: 'rgba(196,128,105,0.45)', backgroundColor: 'rgba(255,231,181,0.88)' },
  animeSpeedGroup: { position: 'absolute', top: '31%', gap: 7 },
  animeSpeedGroupLeft: { left: '1%', alignItems: 'flex-start' },
  animeSpeedGroupRight: { right: '1%', alignItems: 'flex-end' },
  animeSpeedLine: { height: 3, borderRadius: 3, backgroundColor: 'rgba(211, 111, 82, 0.8)' },

  animeGloomLines: { position: 'absolute', left: '17%', top: '9%', flexDirection: 'row', gap: 7, alignItems: 'flex-start' },
  animeGloomLine: { width: 3, height: 27, borderRadius: 3, backgroundColor: 'rgba(103, 82, 120, 0.56)' },
  animeGloomLineShort: { height: 18 },

  pullStatus: { position: 'absolute', bottom: -2, left: 0, right: 0, alignItems: 'center', zIndex: 4 },
  pullStatusText: { color: '#8A6672', fontSize: 12, fontWeight: '900', backgroundColor: 'rgba(255,248,232,0.78)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10 },
  pullParticleBurst: { zIndex: 12 },
  timeParticleBurst: { zIndex: 7 },
  homeMoodBadge: { position: 'absolute', right: -4, top: 34, minHeight: 44, overflow: 'hidden' },
  homeMoodBadgeContent: { minHeight: 44, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  homeMoodBadgeText: { color: '#67465A', fontSize: 13, fontWeight: '900' },
  gamePressed: { transform: [{ scale: 0.95 }], opacity: 0.9 },
  touchBubble: { position: 'absolute', top: 15, left: 14, maxWidth: 180, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 16, backgroundColor: '#FFFDF5', borderWidth: 1, borderColor: '#E8CDB4', transform: [{ rotate: '-3deg' }] },
  touchBubbleText: { color: '#5E4057', fontSize: 12, fontWeight: '900' },
  touchHand: { position: 'absolute', right: 19, bottom: 21, color: '#F0B99E', fontSize: 54, fontWeight: '900', transform: [{ rotate: '-18deg' }], textShadowColor: 'rgba(89,55,63,0.22)', textShadowRadius: 3 },
  touchHearts: { position: 'absolute', bottom: 16, right: 16, flexDirection: 'row' },
  touchHeart: { color: '#D57889', fontSize: 21, marginLeft: 5 },
  pressed: { opacity: 0.9, transform: [{ translateY: 1 }, { scale: 0.95 }] },
});
