import { Platform, StyleSheet } from 'react-native';

const DESIGN_WIDTH = 430;
const COLLECTION_BOARD_TOP = 78;

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#E7D3BC' },
  outer: { flex: 1, width: '100%', height: '100%', alignItems: 'center', justifyContent: 'flex-start', backgroundColor: Platform.OS === 'web' ? '#E7D3BC' : '#FFF7EA' },
  appViewport: { position: 'relative', overflow: 'hidden', backgroundColor: '#E7D3BC', ...(Platform.OS === 'web' ? { boxShadow: '0 16px 48px rgba(81, 48, 54, 0.18)' } : {}) },
  appShell: { position: 'absolute', top: 0, left: 0, width: DESIGN_WIDTH, backgroundColor: '#D8A46F', overflow: Platform.OS === 'web' ? ('clip' as any) : 'hidden', transformOrigin: 'top left' },
  appBaseLayer: { flex: 1, position: 'relative' },
  incidentScreenLayer: { ...StyleSheet.absoluteFillObject, zIndex: 160, backgroundColor: '#211827' },
  globalHeaderPlaceholder: { minHeight: 74 },
  appShellBackground: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  collectionReferenceBackground: { ...StyleSheet.absoluteFillObject, width: DESIGN_WIDTH, height: '100%' },
  loadingOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 140, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(76,53,71,0.36)' },
  loadingCard: { width: 286, minHeight: 290, paddingHorizontal: 24, paddingTop: 15, paddingBottom: 22, borderRadius: 32, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF8E9', borderWidth: 1.5, borderColor: '#DDBA94', shadowColor: '#4D3246', shadowOpacity: 0.28, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 14 },
  loadingMascotWrap: { width: 210, height: 198, alignItems: 'center', justifyContent: 'flex-end' },
  loadingMascotWrapCompact: { width: 90, height: 62, marginBottom: -9 },
  loadingMascotImage: { width: 185, height: 175 },
  loadingMascotImageCompact: { width: 68, height: 58 },
  loadingDots: { height: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  loadingDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#735574' },
  loadingTitle: { color: '#5D405B', fontSize: 18, lineHeight: 23, fontWeight: '900', marginTop: 2 },
  loadingText: { color: '#98737E', fontSize: 10, lineHeight: 15, fontWeight: '800', marginTop: 4 },
  pressableFocusReset: { outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  panelStretchImage: { width: '100%', height: '100%' },
  onboardingOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 115, alignItems: 'center', justifyContent: 'center' },
  onboardingBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(67,44,61,0.025)' },
  favoriteCard: { position: 'absolute', top: 32, left: 14, right: 14, bottom: 24, paddingHorizontal: 16, paddingTop: 18, paddingBottom: 16, borderRadius: 30, alignItems: 'center', backgroundColor: 'rgba(255,249,236,0.2)', borderWidth: 1.6, borderColor: 'rgba(255,255,250,0.54)', shadowColor: '#4D3246', shadowOpacity: 0.17, shadowRadius: 16, shadowOffset: { width: 0, height: 10 }, elevation: 16, ...(Platform.OS === 'web' ? ({ backdropFilter: 'blur(3px) saturate(1.03)' } as any) : {}) },
  favoriteGlassSheen: { position: 'absolute', top: 9, left: 18, right: 18, height: 86, borderRadius: 28, backgroundColor: 'rgba(255,255,255,0.035)', borderTopWidth: 1.4, borderColor: 'rgba(255,255,255,0.3)' },
  onboardingKicker: { color: '#A0797F', fontSize: 8, fontWeight: '900', letterSpacing: 1.8 },
  favoriteTitle: { color: '#553B59', fontSize: 23, lineHeight: 29, fontWeight: '900', marginTop: 4 },
  favoriteLead: { width: 320, color: '#8D6C76', fontSize: 16, lineHeight: 23, fontWeight: '800', textAlign: 'center', marginTop: 4, marginBottom: 10 },
  favoriteCarousel: { width: '100%', minHeight: 366, marginTop: -2 },
  onboardingPrimaryButton: { width: '100%', minHeight: 48, marginTop: 10, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: '#6B547D', borderWidth: 1.2, borderColor: '#E3C7D5', shadowColor: '#4E365B', shadowOpacity: 0.2, shadowRadius: 7, shadowOffset: { width: 0, height: 4 }, elevation: 5 },
  onboardingPrimaryButtonPressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
  onboardingPrimaryText: { color: '#FFF9EC', fontSize: 16, lineHeight: 22, fontWeight: '900', letterSpacing: 0.4 },
  guideOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 100 },
  guideNavHighlight: { position: 'absolute', bottom: Platform.OS === 'web' ? 17 : 10, height: 60, padding: 3, borderRadius: 20, borderWidth: 2, borderColor: '#C9778B', backgroundColor: 'rgba(255,240,225,0.18)', zIndex: 104, shadowColor: '#6A4158', shadowOpacity: 0.25, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 10 },
  guideNavHighlightInner: { flex: 1, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(255,247,228,0.92)' },
  guideCard: { position: 'absolute', left: 10, right: 10, paddingHorizontal: 28, paddingTop: 23, paddingBottom: 25, shadowColor: '#4E3449', shadowOpacity: 0.23, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 11 },
  guideCardImage: { width: '100%', height: '100%' },
  guideCardBottom: { bottom: 84, minHeight: 210 },
  guideCardTop: { top: 78, minHeight: 176 },
  guideHeadingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  guideStep: { color: '#A3727E', fontSize: 13, lineHeight: 18, fontWeight: '900', letterSpacing: 1.1 },
  guideSkip: { color: '#91717B', fontSize: 13, lineHeight: 18, fontWeight: '900', textDecorationLine: 'underline' },
  guideTitle: { color: '#5C405B', fontSize: 19, lineHeight: 26, fontWeight: '900', marginTop: 5 },
  guideBody: { color: '#876872', fontSize: 16, lineHeight: 24, fontWeight: '800', marginTop: 5 },
  guideButton: { alignSelf: 'flex-end', width: 142, height: 46, marginTop: 10, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  guideButtonText: { color: '#FFF9EC', fontSize: 16, lineHeight: 22, fontWeight: '900' },
  openingScreen: { ...StyleSheet.absoluteFillObject, zIndex: 100, overflow: 'hidden' },
  openingBackdrop: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  openingTapSurface: { ...StyleSheet.absoluteFillObject, zIndex: 6, backgroundColor: 'transparent' },
  openingTitleWrap: { position: 'absolute', top: 34, left: 24, right: 24, alignItems: 'center', zIndex: 8 },
  openingTitlePlaque: { width: 310, height: 129, alignItems: 'center', justifyContent: 'center', paddingTop: 4 },
  openingLogoImage: { width: 280, height: 99 },
  openingTitle: { color: '#5A3A69', fontSize: 43, lineHeight: 45, fontWeight: '900', letterSpacing: 2.2, textShadowColor: 'rgba(255,249,231,0.72)', textShadowRadius: 3 },
  openingTitleSub: { color: '#8B647E', fontSize: 9, fontWeight: '900', letterSpacing: 2.6, marginTop: 1 },
  openingTagline: { color: '#694C5E', fontSize: 12, fontWeight: '900', marginTop: -7, textShadowColor: 'rgba(255,250,233,0.9)', textShadowRadius: 4 },
  openingScene: { position: 'absolute', top: 0, left: 0, right: 0, height: 428 },
  openingOpenedBox: { position: 'absolute', top: 0, left: '50%', width: 360, height: 360, marginLeft: -180, zIndex: 1 },
  openingKeyDecoration: { position: 'absolute' },
  openingMobby: { position: 'absolute', top: 69, left: '50%', width: 222, height: 252, marginLeft: -111, zIndex: 3 },
  openingUnopenedPackage: { position: 'absolute', left: '50%', zIndex: 4 },
  openingStartWrap: { position: 'absolute', left: 18, right: 18, bottom: 18, alignItems: 'center', zIndex: 9 },
  openingStartButton: { width: 292, height: 126, alignItems: 'center', justifyContent: 'center', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  openingStartLoading: { opacity: 0.78 },
  openingStartPressed: { transform: [{ scale: 0.96 }] },
  openingStartPlaque: { width: 292, height: 126, alignItems: 'center', justifyContent: 'center', paddingTop: 4 },
  openingStartTitle: { color: '#64425D', fontSize: 16, fontWeight: '900', letterSpacing: 1.7 },
  openingStartSub: { color: '#9A707C', fontSize: 10, fontWeight: '900', marginTop: 3 },
  header: { minHeight: 74, paddingHorizontal: 16, paddingTop: 7, paddingBottom: 8, flexDirection: 'row', alignItems: 'center', backgroundColor: 'transparent', borderBottomWidth: 0 },
  logo: { width: 103, height: 50, marginLeft: -5 },
  headerCopy: { flex: 1, marginLeft: 2 },
  headerKicker: { color: '#806174', fontSize: 9, fontWeight: '900', letterSpacing: 1.6 },
  headerDay: { color: '#49334E', fontSize: 12, fontWeight: '900', marginTop: 3 },
  headerDot: { color: '#D18A9C' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  soundButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,249,235,0.88)', alignItems: 'center', justifyContent: 'center', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent', shadowColor: '#66475D', shadowOpacity: 0.12, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 3 },
  soundButtonMuted: { backgroundColor: 'rgba(238,231,225,0.92)' },
  soundButtonText: { color: '#76536F', fontSize: 19, lineHeight: 21, fontWeight: '900' },
  soundButtonTextMuted: { color: '#9B8687' },
  soundMutedSlash: { position: 'absolute', width: 23, height: 2, borderRadius: 1, backgroundColor: '#A1777F', transform: [{ rotate: '-42deg' }] },
  caseHeaderButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,253,246,0.9)', alignItems: 'center', justifyContent: 'center', shadowColor: '#66475D', shadowOpacity: 0.12, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 3 },
  caseHeaderIcon: { width: 21, height: 21, tintColor: '#76536F' },
  caseHeaderBadge: { position: 'absolute', right: -3, top: -5, width: 16, height: 16, borderRadius: 8, backgroundColor: '#D8898E', borderWidth: 1.2, borderColor: '#FFF8EC', alignItems: 'center', justifyContent: 'center' },
  caseHeaderBadgeWaiting: { backgroundColor: '#B6A2B0' },
  caseHeaderBadgeText: { color: '#FFF', fontSize: 9, lineHeight: 11, fontWeight: '900' },
  bellButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,253,246,0.9)', alignItems: 'center', justifyContent: 'center', shadowColor: '#66475D', shadowOpacity: 0.12, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 3 },
  bellIcon: { width: 21, height: 21 },
  bellBadge: { position: 'absolute', right: -4, top: -6, width: 17, height: 17, borderRadius: 9, backgroundColor: '#E47884', borderWidth: 1.5, borderColor: '#FFF8EC', alignItems: 'center', justifyContent: 'center' },
  bellBadgeText: { color: '#FFF', fontSize: 9, fontWeight: '900' },
  notificationOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 80 },
  notificationBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(63,42,56,0.2)' },
  notificationPopup: { position: 'absolute', top: 61, left: 12, right: 12, padding: 10, borderRadius: 23, backgroundColor: '#FFF9EC', borderWidth: 1.4, borderColor: '#DCB991', shadowColor: '#4E354A', shadowOpacity: 0.28, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 14 },
  notificationPointer: { position: 'absolute', top: -7, right: 20, width: 16, height: 16, backgroundColor: '#FFF9EC', borderLeftWidth: 1.2, borderTopWidth: 1.2, borderColor: '#DCB991', transform: [{ rotate: '45deg' }] },
  notificationHeader: { minHeight: 49, paddingLeft: 6, paddingRight: 2, paddingBottom: 7, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  notificationTitle: { color: '#5B3E59', fontSize: 17, lineHeight: 21, fontWeight: '900', letterSpacing: 0.5 },
  notificationSubtitle: { color: '#7F5C68', fontSize: 13, lineHeight: 18, fontWeight: '700', marginTop: 2 },
  notificationCloseButton: { width: 31, height: 31, borderRadius: 12, backgroundColor: '#F3E3D5', alignItems: 'center', justifyContent: 'center', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  notificationCloseText: { color: '#775568', fontSize: 23, lineHeight: 25, marginTop: -2 },
  notificationItem: { minHeight: 98, marginTop: 5, outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  notificationItemPaper: { width: '100%', minHeight: 98, paddingHorizontal: 17, paddingVertical: 12, flexDirection: 'row', alignItems: 'center' },
  notificationItemFeatured: {},
  notificationItemPressed: { opacity: 0.76, transform: [{ scale: 0.985 }] },
  notificationIcon: { width: 42, height: 42, marginRight: 9, borderRadius: 15, alignItems: 'center', justifyContent: 'center', borderWidth: 1.2 },
  notificationIconTime: { backgroundColor: '#F1D4A6', borderColor: '#D3A56C' },
  notificationIconCollection: { backgroundColor: '#EAD9E6', borderColor: '#C9A8C0' },
  notificationIconCase: { backgroundColor: '#E7D2D7', borderColor: '#BE8B9C' },
  notificationIconText: { color: '#6A4C68', fontSize: 20, fontWeight: '900' },
  notificationCopy: { flex: 1, minWidth: 0 },
  notificationItemHeading: { flexDirection: 'row', alignItems: 'center' },
  notificationKicker: { color: '#795463', fontSize: 13, lineHeight: 18, fontWeight: '800', letterSpacing: 0.5 },
  notificationLiveBadge: { marginLeft: 7, paddingHorizontal: 7, paddingVertical: 2, borderRadius: 8, backgroundColor: '#E47780' },
  notificationNewBadge: { marginLeft: 7, paddingHorizontal: 7, paddingVertical: 2, borderRadius: 8, backgroundColor: '#8C5D83' },
  notificationLiveText: { color: '#FFF9ED', fontSize: 13, lineHeight: 18, fontWeight: '900' },
  notificationItemTitle: { color: '#50364D', fontSize: 17, lineHeight: 23, fontWeight: '800', marginTop: 2 },
  notificationItemBody: { color: '#765762', fontSize: 13, lineHeight: 18, fontWeight: '600', marginTop: 1 },
  notificationChevron: { color: '#A98787', fontSize: 25, lineHeight: 27, marginLeft: 5 },
  noticeToast: { position: 'absolute', zIndex: 30, top: 78, left: 15, right: 15, minHeight: 44, paddingHorizontal: 13, borderRadius: 15, backgroundColor: '#503B65', flexDirection: 'row', alignItems: 'center', shadowColor: '#3E294D', shadowOpacity: 0.23, shadowRadius: 9, shadowOffset: { width: 0, height: 5 }, elevation: 8 },
  noticeToastText: { flex: 1, color: '#FFF8ED', fontSize: 11, fontWeight: '800' },
  noticeToastClose: { color: '#F5CED2', fontSize: 21, marginLeft: 8 },
  screenBody: { flex: 1 },
  scrollContent: { paddingHorizontal: 14, paddingTop: 13, paddingBottom: 105 },
  timeScrollContent: { paddingHorizontal: 14, paddingTop: 0, alignItems: 'center' },
  homeScreenBackground: { flex: 1 },
  brandWrap: { width: 124, height: 48, alignItems: 'flex-start', justifyContent: 'center' },
  headerLogoImage: { width: 120, height: 47 },
  headerSpacer: { flex: 1 },
  brand: { color: '#5A3A6A', fontSize: 25, lineHeight: 28, fontWeight: '900', letterSpacing: 1.3 },
  brandSub: { color: '#806189', fontSize: 10, fontWeight: '900', letterSpacing: 2.2, marginTop: -2 },
  homeRoom: { flex: 1, position: 'relative', overflow: 'hidden' },
  homeShelfBase: { position: 'absolute', top: '-15%', left: 0, right: 0, width: '100%', height: '100%', zIndex: 0 },
  homeGarland: { position: 'absolute', top: -27, left: 5, width: 430, height: 138, zIndex: 1, opacity: 0.86 },
  homeDecorAsset: { width: '100%', height: '100%' },
  homeEditButton: { position: 'absolute', top: 4, right: 14, zIndex: 24, width: 72, height: 34, alignItems: 'center', justifyContent: 'center' },
  homeEditButtonAsset: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center', paddingBottom: 1 },
  homeEditButtonActive: {},
  homeEditButtonText: { color: '#6B4A62', fontSize: 10, fontWeight: '900', letterSpacing: 0.7 },
  homeEditButtonTextActive: { color: '#FFF9EC', textShadowColor: 'rgba(89,46,56,0.32)', textShadowRadius: 2 },
  homeEditGuide: { position: 'absolute', left: 16, right: 16, bottom: 82, zIndex: 24, minHeight: 54, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(83,58,101,0.95)', borderWidth: 1.2, borderColor: '#E8C9D8', shadowColor: '#3E294D', shadowOpacity: 0.22, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 8 },
  homeEditGuideTitle: { color: '#F7D7E3', fontSize: 13, lineHeight: 18, fontWeight: '900', letterSpacing: 1.2 },
  homeEditGuideText: { color: '#FFF9EB', fontSize: 14, lineHeight: 20, fontWeight: '900', textAlign: 'center', marginTop: 2 },
  // Nine keychains are distributed over two broad rows so the center stage
  // remains clear for the selected Mobby and the shelf below.
  homeWallKeys: { position: 'absolute', top: '7%', left: '7%', right: '7%', height: '43%', flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-start', alignContent: 'flex-start', zIndex: 2 },
  homeWallKey: { width: '20%', height: '43%', alignItems: 'center', justifyContent: 'flex-start', borderRadius: 12, position: 'relative', overflow: 'visible', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  homeWallKeySelected: { backgroundColor: 'rgba(255,244,196,0.34)', shadowColor: '#FFF0A8', shadowOpacity: 0.8, shadowRadius: 9, shadowOffset: { width: 0, height: 0 }, elevation: 4 },
  homeWallKeyHidden: { opacity: 0 },
  homeWallKeyStolen: { zIndex: 18 },
  homeWallKeyReturning: { zIndex: 12 },
  homeWallReturningImage: { opacity: 0.74 },
  homeWallStolenMarker: { position: 'absolute', top: -16, left: -10, right: -10, height: 152, borderRadius: 22, borderWidth: 3, alignItems: 'center', justifyContent: 'center', shadowColor: '#F32D48', shadowOpacity: 0.8, shadowRadius: 14, shadowOffset: { width: 0, height: 0 }, elevation: 16 },
  homeWallStolenGhost: { position: 'absolute', top: 22, width: 92, height: 102, opacity: 0.2, tintColor: '#441723' },
  homeWallStolenGhostSmall: { width: 74, height: 84, top: 28 },
  homeWallBrokenCord: { position: 'absolute', top: 9, left: '50%', width: 48, height: 48, marginLeft: -24 },
  homeWallBrokenCordLeft: { position: 'absolute', left: 13, top: 0, width: 4, height: 30, borderRadius: 2, backgroundColor: '#D83C4D', transform: [{ rotate: '18deg' }] },
  homeWallBrokenCordRight: { position: 'absolute', right: 11, top: 3, width: 4, height: 25, borderRadius: 2, backgroundColor: '#D83C4D', transform: [{ rotate: '-23deg' }] },
  homeWallCaseTag: { position: 'absolute', top: 4, left: 4, paddingHorizontal: 6, paddingVertical: 3, borderRadius: 6, backgroundColor: '#27131D', borderWidth: 1, borderColor: '#FF8994' },
  homeWallCaseTagText: { color: '#FFE6D7', fontSize: 9, fontWeight: '900', letterSpacing: 0.6 },
  homeWallStolenBand: { position: 'absolute', left: -8, right: -8, top: 54, height: 35, backgroundColor: '#B8273E', borderTopWidth: 2, borderBottomWidth: 2, borderColor: '#FFD0B8', alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-8deg' }] },
  homeWallStolenBandText: { color: '#FFF9E8', fontSize: 14, fontWeight: '900', letterSpacing: 1.2 },
  homeWallStolenName: { position: 'absolute', left: 2, right: 2, bottom: 23, color: '#FFF1DE', fontSize: 12, fontWeight: '900', textAlign: 'center', textShadowColor: '#35101B', textShadowRadius: 3 },
  homeWallResume: { position: 'absolute', bottom: 4, color: '#FFCFB6', fontSize: 10, fontWeight: '900', letterSpacing: 0.1 },
  homeDecorationEditable: { borderWidth: 1.2, borderColor: 'rgba(107,84,125,0.48)', borderStyle: 'dashed', backgroundColor: 'rgba(255,250,232,0.18)' },
  homeDecorationTarget: { borderColor: '#D5748B', backgroundColor: 'rgba(255,225,232,0.34)' },
  homeDecorationEditSelected: { borderWidth: 2.5, borderStyle: 'solid', borderColor: '#6B547D', backgroundColor: 'rgba(255,244,196,0.56)', shadowColor: '#FFF0A8', shadowOpacity: 0.88, shadowRadius: 10, shadowOffset: { width: 0, height: 0 }, elevation: 7 },
  homeSlotBadge: { position: 'absolute', top: -8, right: -5, width: 20, height: 20, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: '#6B547D', borderWidth: 1.5, borderColor: '#FFF9EA', zIndex: 8 },
  homeSlotBadgeText: { color: '#FFF', fontSize: 9, fontWeight: '900' },
  homeWallHook: { position: 'absolute', top: -25, left: '50%', width: 54, height: 81, marginLeft: -27, zIndex: 0 },
  homeWallKeySwing: { alignItems: 'center', transformOrigin: '50% 0%', marginTop: 11 },
  // The hook plate's round center is the hanging point. Start each keychain
  // there so the chain visibly comes out of the center of the wood hook.
  homeWallKeyImage: { width: 96, height: 106 },
  homeWallSmallKeyImage: { width: 76, height: 84 },
  // The wall image has its first wooden shelf directly below the key pegs.
  // Keep the plush feet on that shelf board instead of letting them fall onto
  // the rug at the bottom of the room.
  // The base image's visible top surface sits just below its alpha edge;
  // this fractional offset puts the visible foot soles on that surface.
  // The transparent base's top surface sits just below the artwork's visual
  // center.  Keep the plush row a little lower so each visible foot meets the
  // wood instead of floating above it (the source images contain transparent
  // padding below the feet).
  homePlushShelf: { position: 'absolute', left: '8%', right: '8%', height: '18%', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', zIndex: 3 },
  homePlushItem: { width: '22%', height: '100%', alignItems: 'center', justifyContent: 'flex-end', borderRadius: 13, position: 'relative', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  homePlushSwing: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'flex-end', transformOrigin: '50% 100%' },
  homePlushItemSelected: { backgroundColor: 'rgba(255,244,196,0.32)', shadowColor: '#FFF0A8', shadowOpacity: 0.8, shadowRadius: 9, shadowOffset: { width: 0, height: 0 }, elevation: 4 },
  homePlushImage: { width: 70, height: 80 },
  homePlushSlotBadge: { top: -5, right: -4 },
  homeSelectablePressed: { opacity: 0.74, transform: [{ scale: 0.96 }] },
  homeCharacterPicker: { position: 'absolute', left: 14, right: 14, bottom: 82, alignItems: 'center', zIndex: 24 },
  homeCharacterPickerCompact: { bottom: 52 },
  homeCharacterSelectButton: { minWidth: 152, minHeight: 47, paddingHorizontal: 17, paddingVertical: 6, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,249,237,0.95)', borderWidth: 1.2, borderColor: '#DDB997', shadowColor: '#684B4B', shadowOpacity: 0.2, shadowRadius: 6, shadowOffset: { width: 0, height: 3 }, elevation: 4, outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  homeCharacterSelectEyebrow: { color: '#A07B78', fontSize: 8, fontWeight: '900', letterSpacing: 1.1 },
  homeCharacterSelectName: { color: '#6B4A62', fontSize: 13, fontWeight: '900', marginTop: 1, maxWidth: 170 },
  homeCharacterSelectHint: { color: '#9C7774', fontSize: 13, lineHeight: 17, fontWeight: '800', marginTop: 1 },
  homeCharacterPickerOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 70 },
  homeCharacterPickerBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(54,36,54,0.24)', zIndex: 30 },
  homeCharacterPickerMenu: { position: 'absolute', left: 12, right: 12, bottom: 112, height: 334, paddingHorizontal: 24, paddingTop: 20, paddingBottom: 22, shadowColor: '#3E294D', shadowOpacity: 0.2, shadowRadius: 14, shadowOffset: { width: 0, height: 6 }, elevation: 10, zIndex: 40 },
  homeCharacterPickerMenuCompact: { bottom: 100 },
  homeCharacterPickerMenuHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingLeft: 6, marginBottom: 8 },
  homeCharacterPickerTitle: { color: '#6B4A62', fontSize: 14, fontWeight: '900', letterSpacing: 0.4 },
  homeCharacterPickerClose: { width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F4DFD7' },
  homeCharacterPickerCloseText: { color: '#76516C', fontSize: 18, lineHeight: 20, marginTop: -1 },
  homeCharacterOptions: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 5 },
  homeCharacterOption: { width: '31.8%', minHeight: 75, paddingVertical: 4, borderRadius: 16, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'transparent' },
  homeCharacterOptionSelected: { backgroundColor: '#F8E7BD', borderColor: '#DCA66D' },
  homeCharacterOptionImage: { width: 51, height: 55 },
  homeCharacterOptionName: { width: '100%', color: '#76516C', fontSize: 9, fontWeight: '900', textAlign: 'center', marginTop: 1 },
  homeMainCharacter: { position: 'absolute', left: '50%', bottom: 90, width: 220, height: 250, marginLeft: -110, zIndex: 8 },
  homeMainCharacterCompact: { bottom: 60, width: 178, height: 198, marginLeft: -89 },
  homeMainCharacterPullable: { alignItems: 'center', justifyContent: 'flex-end', overflow: 'visible' },
  homeMainCharacterEditing: { opacity: 0.13 },
  homeReactionBubble: { position: 'absolute', right: 10, width: 120, paddingHorizontal: 10, paddingVertical: 9, borderRadius: 15, backgroundColor: '#FFFDF5', borderWidth: 1, borderColor: '#E8CDB4', transform: [{ rotate: '-2deg' }], zIndex: 12 },
  homeReactionTailBorder: { position: 'absolute', left: 14, bottom: -22, width: 0, height: 0, borderLeftWidth: 10, borderRightWidth: 10, borderTopWidth: 24, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderTopColor: '#E8CDB4', transform: [{ rotate: '30deg' }] },
  homeReactionTail: { position: 'absolute', left: 15, bottom: -18, width: 0, height: 0, borderLeftWidth: 9, borderRightWidth: 9, borderTopWidth: 21, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderTopColor: '#FFFDF5', transform: [{ rotate: '30deg' }], zIndex: 1 },
  homeReactionBubbleText: { color: '#5E4057', fontSize: 10, lineHeight: 14, fontWeight: '900', textAlign: 'center' },
  dailyHomeToggle: { position: 'absolute', top: 4, left: 14, zIndex: 26, minWidth: 92, height: 34, paddingHorizontal: 12, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,249,236,0.96)', borderWidth: 1.2, borderColor: '#DAB897', shadowColor: '#64495C', shadowOpacity: 0.16, shadowRadius: 5, shadowOffset: { width: 0, height: 3 }, elevation: 5 },
  dailyHomeToggleBurst: { position: 'absolute', top: 4, left: 14, width: 92, height: 34, zIndex: 27 },
  dailyHomeToggleText: { color: '#6B4A62', fontSize: 9, fontWeight: '900', letterSpacing: 0.7 },
  dailyHomePanel: { position: 'absolute', top: 43, left: 10, right: 10, bottom: 82, zIndex: 64, borderRadius: 24, overflow: 'hidden', backgroundColor: 'rgba(255,249,236,0.98)', borderWidth: 1.4, borderColor: '#DDBB98', shadowColor: '#4D3448', shadowOpacity: 0.26, shadowRadius: 13, shadowOffset: { width: 0, height: 7 }, elevation: 13 },
  dailyHomePanelContent: { padding: 12, gap: 12, paddingBottom: 24 },
  dailyStampWrap: { position: 'relative', overflow: 'visible' },
  dailyStampCard: { borderRadius: 20, padding: 16, backgroundColor: '#FFF9EC', borderWidth: 1, borderColor: '#E6C8A7' },
  dailyReadableHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 12 },
  dailyReadableTitle: { flexShrink: 1, color: '#5C4055', fontSize: 17, lineHeight: 23, fontWeight: '900' },
  dailyReadableCaption: { color: '#9B777C', fontSize: 13, lineHeight: 18, fontWeight: '800' },
  dailyStampRow: { flexDirection: 'row', justifyContent: 'space-between' },
  dailyStampCell: { flex: 1, minWidth: 0, alignItems: 'center' },
  dailyStampCircle: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F0E4D8', borderWidth: 1, borderColor: '#DABFA8' },
  dailyStampCircleDone: { backgroundColor: '#D98494', borderColor: '#C66D82' },
  dailyStampDay: { color: '#8D7472', fontSize: 13, lineHeight: 18, fontWeight: '900' },
  dailyStampDayDone: { color: '#FFF9EC' },
  dailyMissionPanel: { borderRadius: 20, padding: 16, backgroundColor: '#FBF3F5', borderWidth: 1, borderColor: '#E4C4CC' },
  dailyMissionRow: { minHeight: 64, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E5CBD1' },
  dailyMissionCheck: { width: 28, height: 28, borderRadius: 14, borderWidth: 2, borderColor: '#CBAAB3', alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  dailyMissionCheckDone: { backgroundColor: '#8C6683', borderColor: '#8C6683' },
  dailyMissionCheckText: { color: '#FFF', fontSize: 13, lineHeight: 18, fontWeight: '900' },
  dailyMissionCopy: { flex: 1 },
  dailyMissionLabel: { color: '#684C60', fontSize: 14, lineHeight: 20, fontWeight: '800' },
  dailyMissionCaption: { color: '#A17D87', fontSize: 13, lineHeight: 18, fontWeight: '700', marginTop: 2 },
  dailyMissionBonus: { marginTop: 12, paddingVertical: 9, paddingHorizontal: 8, borderRadius: 12, alignItems: 'center', backgroundColor: '#E9DADF' },
  dailyMissionBonusDone: { backgroundColor: '#76546F' },
  dailyMissionBonusText: { color: '#8F6F79', fontSize: 13, lineHeight: 18, fontWeight: '900', textAlign: 'center' },
  dailyMissionBonusTextDone: { color: '#FFF9EC' },
  dailyMobbyTimeCard: { minHeight: 64, paddingHorizontal: 15, paddingVertical: 11, borderRadius: 18, backgroundColor: '#6B547D', borderWidth: 1.2, borderColor: '#D8BDD4' },
  dailyMobbyTimeTitle: { color: '#FFF9EC', fontSize: 17, lineHeight: 23, fontWeight: '900', letterSpacing: 1 },
  dailyMobbyTimeText: { color: '#F0DCE6', fontSize: 13, lineHeight: 18, fontWeight: '800', marginTop: 3 },
  dailyPending: { minHeight: 55, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 16, backgroundColor: '#F6E4C8', borderWidth: 1, borderColor: '#DDBB8B' },
  dailyPendingTitle: { color: '#6A4B5E', fontSize: 17, lineHeight: 23, fontWeight: '900' },
  dailyPendingText: { color: '#92716F', fontSize: 13, lineHeight: 18, fontWeight: '700', marginTop: 2 },
  dailyDisabled: { opacity: 0.48 },
  dailyLoadingText: { color: '#987683', fontSize: 13, lineHeight: 18, fontWeight: '800', textAlign: 'center', marginTop: 7 },
  wallFlightOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 60, overflow: 'hidden' },
  wallFlightStatus: { position: 'absolute', top: 84, left: 72, right: 72, minHeight: 38, borderRadius: 18, backgroundColor: 'rgba(83,58,101,0.94)', alignItems: 'center', justifyContent: 'center', zIndex: 6, borderWidth: 1, borderColor: '#E9C7DA' },
  wallFlightStatusText: { color: '#FFF8E9', fontSize: 14, lineHeight: 20, fontWeight: '900', letterSpacing: 0.4 },
  wallFlightItem: { position: 'absolute', left: 0, top: 0, width: 84, height: 92, alignItems: 'center', justifyContent: 'center', zIndex: 3 },
  wallFlightImage: { width: 84, height: 92 },
  wallFlightSmallImage: { width: 66, height: 73 },
  wallFlightTrail: { position: 'absolute', left: 0, top: 0, width: 84, height: 92, borderRadius: 46, backgroundColor: 'rgba(255,242,166,0.5)', borderWidth: 4, borderColor: '#FFF1A8' },
  wallLandingBurst: { position: 'absolute', width: 76, height: 76, borderRadius: 40, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,244,176,0.44)', borderWidth: 3, borderColor: '#FFF4B6', zIndex: 2 },
  wallLandingBurstText: { color: '#FFF8CA', fontSize: 42, fontWeight: '900', textShadowColor: '#C7748D', textShadowRadius: 8 },
  collectionHeaderBar: { position: 'absolute', top: 8, left: 18, right: 18, height: 39, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', zIndex: 10 },
  collectionScreenBackground: { flex: 1, backgroundColor: 'transparent' },
  collectionScrollContent: { flex: 1, position: 'relative' },
  collectionScrollInner: { position: 'relative', paddingBottom: 96 },
  reactionCollectionCard: { position: 'absolute', left: 15, right: 15, minHeight: 176, padding: 14, borderRadius: 22, backgroundColor: 'rgba(255,249,236,0.97)', borderWidth: 1.3, borderColor: '#DDBB98', shadowColor: '#4D3448', shadowOpacity: 0.18, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 7, zIndex: 12 },
  reactionCollectionHeading: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 },
  reactionCollectionTitle: { color: '#5C4055', fontSize: 15, lineHeight: 19, fontWeight: '900' },
  reactionCollectionText: { color: '#8D6878', fontSize: 9, lineHeight: 13, fontWeight: '800', marginTop: 2 },
  reactionCollectionNext: { flexShrink: 1, maxWidth: 145, color: '#76546F', fontSize: 9, lineHeight: 13, fontWeight: '900', textAlign: 'right' },
  reactionMilestoneRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 6, marginTop: 12 },
  reactionMilestone: { flex: 1, minHeight: 66, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E9DFD9', borderWidth: 1, borderColor: '#D0BDB6' },
  reactionMilestoneClaimable: { backgroundColor: '#7A5A78', borderColor: '#E5C7D8', shadowColor: '#6B4664', shadowOpacity: 0.2, shadowRadius: 5, shadowOffset: { width: 0, height: 3 }, elevation: 4 },
  reactionMilestoneClaimed: { backgroundColor: '#D9C8B9', borderColor: '#C7AE99' },
  reactionMilestoneText: { color: '#654A5E', fontSize: 14, fontWeight: '900' },
  reactionMilestoneState: { color: '#886D78', fontSize: 7, fontWeight: '900', marginTop: 3 },
  reactionMilestoneTextActive: { color: '#FFF9EC' },
  collectionBoardShadow: { position: 'absolute', top: 84, left: 30, width: 380, borderRadius: 36, backgroundColor: 'rgba(72,44,31,0.24)', shadowColor: '#3D281F', shadowOpacity: 0.42, shadowRadius: 22, shadowOffset: { width: 0, height: 10 }, elevation: 11, zIndex: 1 },
  collectionDisplayBoard: { position: 'absolute', top: COLLECTION_BOARD_TOP, left: 25, width: 390, borderRadius: 36, overflow: 'hidden', zIndex: 2 },
  collectionHeaderCopy: { width: 145, height: 37, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, paddingBottom: 1 },
  collectionHeaderTitle: { color: '#563C50', fontSize: 14, lineHeight: 18, fontWeight: '900', letterSpacing: 0.2, fontFamily: 'MochiyPopOne_400Regular' },
  collectionModeTabs: { height: 36, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 7, paddingVertical: 5 },
  collectionModeTab: { minWidth: 74, height: 25, paddingHorizontal: 10, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  collectionModeTabActive: { backgroundColor: '#70556E', shadowColor: '#513B4E', shadowOpacity: 0.16, shadowRadius: 3, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  collectionModeText: { color: '#876C7D', fontSize: 10, fontWeight: '800' },
  collectionModeTextActive: { color: '#FFF9ED' },
  collectionKeySizeTabs: { position: 'absolute', top: 51, right: 27, height: 25, flexDirection: 'row', alignItems: 'center', gap: 3, zIndex: 10 },
  collectionKeySizeLabel: { color: '#8B6B79', fontSize: 8, fontWeight: '800', marginRight: 2 },
  collectionKeySizeTab: { minWidth: 29, height: 23, paddingHorizontal: 8, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  collectionKeySizeTabActive: { backgroundColor: 'rgba(255,248,232,0.9)' },
  collectionKeySizeText: { color: '#967584', fontSize: 9, fontWeight: '800' },
  collectionKeySizeTextActive: { color: '#65475E' },
  collectionDisplay: { position: 'absolute', top: 0, left: 0, right: 0, backgroundColor: 'transparent', overflow: 'visible', zIndex: 3 },
  collectionDisplayPlush: { backgroundColor: 'transparent' },
  keyCollectionGrid: { ...StyleSheet.absoluteFillObject },
  collectionKeyItem: { width: 104, alignItems: 'center' },
  collectionKeyItemAnchored: { position: 'absolute' },
  collectionKeyPressable: { alignItems: 'center', outlineColor: 'transparent', outlineWidth: 0 },
  collectionKeySwing: { alignItems: 'center', transformOrigin: '50% 0%' },
  collectionKeyHookOwned: { height: 0 },
  collectionKeyBody: { width: 55, height: 70, borderRadius: 22, borderWidth: 1.5, borderColor: 'rgba(91,64,75,0.28)', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  collectionKeyBodyOwned: { width: 104, height: 122, borderRadius: 0, borderWidth: 0, borderColor: 'transparent', backgroundColor: 'transparent', overflow: 'visible' },
  collectionKeySelected: { transform: [{ scale: 1.06 }] },
  collectionKeyImage: { width: 104, height: 122 },
  collectionSmallKeyImage: { width: 81, height: 95 },
  collectionKeyName: { width: 104, color: '#503645', fontSize: 8, fontWeight: '700', textAlign: 'center', marginTop: 1, textShadowColor: '#FFF4DC', textShadowRadius: 2 },
  collectionLocked: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(96,80,94,0.52)', alignItems: 'center', justifyContent: 'center' },
  collectionLockedText: { color: '#FFF7E6', fontSize: 27, fontWeight: '900' },
  plushCollectionShelf: { ...StyleSheet.absoluteFillObject },
  plushCollectionItem: { position: 'absolute', width: 110, height: 134, alignItems: 'center' },
  plushCollectionBody: { width: 110, height: 120, borderRadius: 28, borderWidth: 1.4, borderColor: 'rgba(86,58,58,0.27)', alignItems: 'center', justifyContent: 'flex-end', overflow: 'hidden' },
  plushCollectionBodyOwned: { width: 110, height: 120, borderRadius: 0, borderWidth: 0, borderColor: 'transparent', backgroundColor: 'transparent', overflow: 'visible' },
  plushCollectionSelected: { transform: [{ scale: 1.05 }] },
  plushCollectionImage: { position: 'absolute', width: 110, height: 120 },
  collectionPlushName: { width: 110, color: '#503645', fontSize: 8, fontWeight: '700', textAlign: 'center', textShadowColor: '#FFF4DC', textShadowRadius: 2, marginTop: 1 },
  timeBanner: { minHeight: 72, borderRadius: 21, paddingHorizontal: 11, paddingVertical: 9, backgroundColor: '#5B4672', flexDirection: 'row', alignItems: 'center', shadowColor: '#3B294D', shadowOpacity: 0.16, shadowRadius: 7, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  timeBannerClosed: { backgroundColor: '#8D7789' },
  timeBadge: { width: 47, height: 47, borderRadius: 18, backgroundColor: '#F3D6AF', alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  sparkleIcon: { width: 32, height: 32 },
  timeCopy: { flex: 1 },
  timeLabel: { color: '#FFF8EC', fontSize: 16, fontWeight: '900', letterSpacing: 1.2 },
  timeSub: { color: '#EEDBE2', fontSize: 10, fontWeight: '700', marginTop: 3 },
  timeCount: { alignItems: 'flex-end', paddingLeft: 7 },
  timeCountCaption: { color: '#EFDCE3', fontSize: 10, fontWeight: '800' },
  timeCountValue: { color: '#FFF8EC', fontSize: 21, fontWeight: '900', letterSpacing: 1 },
  heroNote: { marginTop: 13, paddingVertical: 11, paddingHorizontal: 17, borderRadius: 18, backgroundColor: '#FFFDF5', borderWidth: 1.2, borderColor: '#E7CFB2', transform: [{ rotate: '-0.5deg' }] },
  notePin: { position: 'absolute', top: -5, left: '50%', width: 12, height: 12, borderRadius: 6, backgroundColor: '#DB9C88', borderWidth: 2, borderColor: '#FFF2DD' },
  heroNoteText: { color: '#5C3B54', fontSize: 15, fontWeight: '900', textAlign: 'center' },
  heroNoteSub: { color: '#A77E7C', fontSize: 10, fontWeight: '700', textAlign: 'center', marginTop: 3 },
  eyebrow: { color: '#9A7485', fontSize: 9, fontWeight: '900', letterSpacing: 1.8 },
  sectionTitleRow: { marginTop: 19, marginBottom: 9, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
  sectionTitle: { color: '#4C3451', fontSize: 19, fontWeight: '900', marginTop: 2 },
  sectionAction: { color: '#A47483', fontSize: 10, fontWeight: '900', paddingBottom: 2 },
  roomCard: { height: 365, borderRadius: 24, overflow: 'hidden', borderWidth: 1.5, borderColor: '#D4AE86', backgroundColor: '#ECD5B6' },
  roomCardImage: { opacity: 0.92 },
  roomShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(255, 244, 219, 0.34)' },
  roomTopline: { paddingHorizontal: 12, paddingTop: 11, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  pill: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12, backgroundColor: '#FFF9E9', borderWidth: 1, borderColor: '#E6C6A0' },
  pillPurple: { backgroundColor: '#6A557E', borderColor: '#5B466E' },
  pillPink: { backgroundColor: '#F5D1D3', borderColor: '#E7AEB6' },
  pillText: { color: '#5A3E55', fontSize: 10, fontWeight: '900' },
  roomCount: { color: '#745467', fontSize: 11, fontWeight: '900', backgroundColor: 'rgba(255,249,232,0.84)', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 10 },
  keyWall: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-around', paddingHorizontal: 14, paddingTop: 8 },
  hangingKey: { width: '19%', alignItems: 'center', marginBottom: 5 },
  hook: { width: 19, height: 25, alignItems: 'center' },
  hookTop: { width: 11, height: 11, borderRadius: 6, borderWidth: 2, borderColor: '#7F6B5F', backgroundColor: '#E9D5B8' },
  hookStem: { width: 3, height: 17, backgroundColor: '#7F6B5F', marginTop: -2, borderRadius: 3 },
  hangingBody: { width: 48, height: 63, borderRadius: 20, borderWidth: 2, borderColor: 'rgba(93,65,77,0.32)', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', shadowColor: '#654A49', shadowOpacity: 0.25, shadowRadius: 3, shadowOffset: { width: 0, height: 2 } },
  hangingBodySelected: { borderColor: '#FFF9DF', borderWidth: 3, transform: [{ scale: 1.05 }] },
  hangingImage: { width: 49, height: 62 },
  hangingUnknown: { color: '#766A6A', fontSize: 26, fontWeight: '900' },
  shelf: { position: 'absolute', left: 12, right: 12, bottom: 43, height: 122, borderRadius: 14, backgroundColor: 'rgba(102,68,55,0.22)', paddingTop: 10 },
  shelfBoard: { position: 'absolute', left: -2, right: -2, bottom: -2, height: 14, borderRadius: 7, backgroundColor: '#8C5E48', borderWidth: 1, borderColor: '#694536' },
  shelfItems: { flex: 1, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'flex-end', paddingHorizontal: 8, paddingBottom: 9 },
  shelfItem: { width: '30%', alignItems: 'center' },
  plushBack: { width: 73, height: 87, borderRadius: 26, alignItems: 'center', justifyContent: 'flex-end', overflow: 'hidden', borderWidth: 1.5, borderColor: 'rgba(83,55,52,0.28)' },
  shelfImage: { width: 75, height: 85 },
  shelfUnknown: { color: '#6E5C5F', fontSize: 28, fontWeight: '900', marginBottom: 20 },
  shelfLabel: { color: '#FFF8EA', fontSize: 9, fontWeight: '900', textShadowColor: '#5A3A35', textShadowRadius: 3, marginTop: 2 },
  roomFooter: { position: 'absolute', left: 12, right: 12, bottom: 10, flexDirection: 'row', justifyContent: 'space-between' },
  roomFooterText: { color: '#6F4D4D', fontSize: 9, fontWeight: '900', backgroundColor: 'rgba(255,248,229,0.76)', paddingHorizontal: 7, paddingVertical: 4, borderRadius: 8 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  tile: { width: '31.5%', marginBottom: 11, padding: 5, borderRadius: 17, backgroundColor: '#FFFDF6', borderWidth: 1, borderColor: '#E8D3B7' },
  tileSelected: { borderColor: '#96709A', backgroundColor: '#F8EDF0', shadowColor: '#76506D', shadowOpacity: 0.16, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  tileImageWrap: { height: 83, borderRadius: 13, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', position: 'relative' },
  tileImage: { width: 77, height: 80 },
  keyLoop: { position: 'absolute', top: 4, width: 11, height: 11, borderRadius: 6, borderWidth: 2, borderColor: 'rgba(87,61,62,0.58)' },
  lockVeil: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(78,63,74,0.54)', alignItems: 'center', justifyContent: 'center' },
  lockText: { color: '#FFF5E8', fontSize: 27, fontWeight: '900' },
  tileName: { color: '#5C3E54', fontSize: 10, fontWeight: '900', marginTop: 5 },
  tileMeta: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 2 },
  tileRarity: { color: '#B07C8B', fontSize: 9, fontWeight: '900' },
  tileCount: { color: '#8D6A6D', fontSize: 9, fontWeight: '900' },
  timeHeader: { alignSelf: 'stretch', height: 110, alignItems: 'center', paddingTop: 1, paddingHorizontal: 18 },
  timeTitle: { color: '#4B304B', fontSize: 22, lineHeight: 25, fontWeight: '900', letterSpacing: 0.4, textAlign: 'center', fontFamily: Platform.select({ ios: 'Hiragino Maru Gothic ProN', default: undefined }) },
  bigTitle: { color: '#4D3455', fontSize: 29, fontWeight: '900', letterSpacing: 1.2, marginTop: 3 },
  timeHeaderSub: { color: '#5D4051', fontSize: 10, lineHeight: 13, fontWeight: '700', marginTop: 0, textAlign: 'center', textShadowColor: '#FFF6E7', textShadowRadius: 4 },
  bigTimer: { marginTop: -2, width: 184, height: 66, alignItems: 'center', justifyContent: 'center', paddingTop: 2 },
  bigTimerLabel: { color: '#694A5C', fontSize: 8, lineHeight: 9, fontWeight: '900' },
  bigTimerValue: { color: '#422A43', fontSize: 24, lineHeight: 26, fontWeight: '900', letterSpacing: 1.4 },
  bigTimerUnit: { color: '#7F5C6D', fontSize: 7, lineHeight: 8, fontWeight: '900', letterSpacing: 0.8 },
  encounterCard: { alignSelf: 'center', paddingTop: 47, paddingHorizontal: 39, paddingBottom: 18 },
  encounterCardImage: { borderRadius: 24 },
  arrivalNotice: { minHeight: 35, marginBottom: 0, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  arrivalNoticeText: { color: '#4E3348', fontSize: 14, lineHeight: 20, fontWeight: '900', textAlign: 'center', textShadowColor: '#FFF4DE', textShadowRadius: 3 },
  encounterScene: { height: 306, borderRadius: 26, overflow: 'visible', alignItems: 'center', justifyContent: 'center', position: 'relative' },
  openingLightLayer: { ...StyleSheet.absoluteFillObject, zIndex: 1, alignItems: 'center', justifyContent: 'center', overflow: 'visible' },
  openingLightBeam: { position: 'absolute', top: 12, width: 154, height: 258, backgroundColor: 'rgba(255,244,176,0.68)', shadowColor: '#FFF6B5', shadowOpacity: 0.96, shadowRadius: 34, shadowOffset: { width: 0, height: 0 }, transformOrigin: 'center' },
  openingLightRay: { position: 'absolute', top: 24, width: 19, height: 238, backgroundColor: 'rgba(255,250,211,0.78)', shadowColor: '#FFFBDA', shadowOpacity: 0.92, shadowRadius: 20, shadowOffset: { width: 0, height: 0 }, transformOrigin: 'center' },
  openingLightRayLeft: { left: '50%', marginLeft: -130 },
  openingLightRayRight: { left: '50%', marginLeft: 111 },
  packageAnimationWrap: { ...StyleSheet.absoluteFillObject, zIndex: 3, alignItems: 'center', justifyContent: 'center', paddingTop: 22 },
  revealPackageTouch: { width: 242, height: 242, alignItems: 'center', justifyContent: 'center', position: 'relative', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  mobbyTimePackageAsset: { width: 224, height: 224 },
  packagePressed: { transform: [{ rotate: '1deg' }, { scale: 0.96 }] },
  packageCaptionSpacer: { height: 15 },
  magicParticles: { ...StyleSheet.absoluteFillObject, zIndex: 4, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingHorizontal: 28 },
  magicParticle: { color: '#FFF7B8', fontSize: 32, fontWeight: '900', textShadowColor: '#D98FA0', textShadowRadius: 8 },
  encounterRewardWrap: { width: 286, height: 312, alignItems: 'center', justifyContent: 'center', zIndex: 3 },
  encounterKeyImage: { width: 286, height: 312 },
  encounterSmallKeyImage: { width: 222, height: 244 },
  encounterPlushImage: { width: 222, height: 246 },
  placementSparkles: { ...StyleSheet.absoluteFillObject, zIndex: 5, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingHorizontal: 18 },
  placementSparkle: { color: '#FFF4A8', fontSize: 27, fontWeight: '900', textShadowColor: '#C96F8B', textShadowRadius: 7 },
  newBadge: { position: 'absolute', left: 7, bottom: 4, width: 72, height: 72, alignItems: 'center', justifyContent: 'center', paddingBottom: 12, transform: [{ rotate: '-7deg' }], zIndex: 5 },
  newBadgeText: { color: '#FFF8ED', fontSize: 11, fontWeight: '900', letterSpacing: 0.6, textShadowColor: 'rgba(91,58,76,0.34)', textShadowRadius: 2 },
  encounterImage: { width: 208, height: 246 },
  encounterBubble: { position: 'absolute', top: -8, right: -18, width: 176, height: 96, paddingHorizontal: 27, paddingTop: 17, paddingBottom: 20, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '3deg' }], zIndex: 6 },
  encounterBubbleTitle: { color: '#4E3048', fontSize: 16, lineHeight: 21, fontWeight: '900', textAlign: 'center', textShadowColor: '#FFF7E7', textShadowRadius: 2 },
  encounterBubbleText: { color: '#694B5A', fontSize: 13, lineHeight: 17, fontWeight: '800', marginTop: 1, textAlign: 'center' },
  encounterOpenButton: { alignSelf: 'center', width: 260, height: 52, borderRadius: 20, overflow: 'hidden', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent', shadowColor: '#6B3F4D', shadowOpacity: 0.28, shadowRadius: 6, shadowOffset: { width: 0, height: 4 }, elevation: 6 },
  encounterOpenButtonAsset: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center', paddingLeft: 20, paddingRight: 48, paddingBottom: 1 },
  encounterOpenButtonText: { color: '#FFF9ED', fontFamily: 'MochiyPopOne_400Regular', fontSize: 16, lineHeight: 22, fontWeight: '900', letterSpacing: 0.15, textAlign: 'center', textShadowColor: 'rgba(92,45,54,0.42)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 2 },
  encounterOpenButtonPressed: { opacity: 0.9, transform: [{ translateY: 2 }, { scale: 0.97 }] },
  encounterOpenButtonDisabled: { opacity: 0.58 },
  primaryButton: { minHeight: 49, borderRadius: 17, backgroundColor: '#6B547D', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', paddingHorizontal: 17 },
  primaryButtonDone: { backgroundColor: '#9A8491' },
  primaryButtonIcon: { width: 22, height: 22, marginRight: 5 },
  primaryButtonText: { color: '#FFF9EC', fontSize: 13, fontWeight: '900' },
  timePrimaryButton: { position: 'absolute', left: 63, bottom: 38, width: 244, height: 46, zIndex: 8, outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  timePrimaryButtonInactive: { opacity: 0.58 },
  timePrimaryButtonText: { color: '#5B3D54', textShadowColor: 'rgba(255,251,232,0.62)', textShadowRadius: 2 },
  assetButtonInner: { width: '100%', height: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, paddingVertical: 8, overflow: 'hidden' },
  touchTop: { paddingTop: 7, paddingBottom: 12 },
  touchTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  touchSub: { color: '#987480', fontSize: 11, fontWeight: '700', marginTop: 3 },
  rarityBadge: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10, marginLeft: 6 },
  rarityBadgeText: { color: '#FFF', fontSize: 11, fontWeight: '900' },
  touchScreenBackground: { flex: 1, backgroundColor: 'transparent' },
  touchScrollContent: { flex: 1, paddingHorizontal: 10, paddingTop: 10, paddingBottom: 82 },
  touchStage: { height: 500, borderRadius: 28, overflow: 'hidden', alignItems: 'center', justifyContent: 'center', position: 'relative' },
  pullableWrap: { width: 332, height: 365, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  pullableStage: { width: 320, height: 320, position: 'relative' },
  // PanResponder turns this view into an accessible button on web. Suppress
  // the browser's default focus ring so a completed pull does not leave a
  // harsh black rectangle over the parchment stage.
  pullableSlot: { ...StyleSheet.absoluteFillObject, width: 320, height: 320, alignItems: 'center', justifyContent: 'center', zIndex: 2, outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  pullableBody: { width: 320, height: 320 },
  pullableFaceLayer: { zIndex: 4 },
  pullableReactionLayer: { ...StyleSheet.absoluteFillObject, zIndex: 5 },
  pullableReactionFrame: { ...StyleSheet.absoluteFillObject },
  pullableReactionBurst: { position: 'absolute', zIndex: 4, left: '18%', top: '18%', width: '64%', height: '64%', borderRadius: 999, borderWidth: 4, borderColor: 'rgba(255, 225, 151, 0.8)' },
  characterPickerButton: { position: 'absolute', zIndex: 20, width: 68, height: 51, alignItems: 'center', justifyContent: 'center' },
  characterPickerButtonAsset: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center', paddingBottom: 1 },
  characterPickerButtonLarge: { left: -68, top: '43%' },
  characterPickerButtonCompact: { left: -68, top: '41%' },
  characterPickerButtonPressed: { transform: [{ scale: 0.94 }], opacity: 0.88 },
  characterPickerCaption: { color: '#8B6D91', fontSize: 8, fontWeight: '800', lineHeight: 11 },
  characterPickerValue: { color: '#68465F', fontSize: 11, fontWeight: '900', lineHeight: 15 },
  animeEffectLayer: { ...StyleSheet.absoluteFillObject, zIndex: 6 },
  animeBurstRayWrap: { ...StyleSheet.absoluteFillObject },
  animeBurstRay: { position: 'absolute', width: 3, borderRadius: 3, backgroundColor: 'rgba(255, 225, 151, 0.88)' },
  animeCheekTrail: { position: 'absolute', top: '39%', gap: 6 },
  animeCheekTrailLeft: { left: '2%', alignItems: 'flex-start', transform: [{ rotate: '-8deg' }] },
  animeCheekTrailRight: { right: '2%', alignItems: 'flex-end', transform: [{ rotate: '8deg' }] },
  animeCheekStroke: { height: 3, borderRadius: 3, borderWidth: 0.7, borderColor: 'rgba(196,128,105,0.45)', backgroundColor: 'rgba(255,231,181,0.88)' },
  animeSpeedGroup: { position: 'absolute', top: '31%', gap: 7 },
  animeSpeedGroupLeft: { left: '1%', alignItems: 'flex-start' },
  animeSpeedGroupRight: { right: '1%', alignItems: 'flex-end' },
  animeSpeedLine: { height: 3, borderRadius: 3, backgroundColor: 'rgba(211, 111, 82, 0.8)' },

  animeGloomLines: { position: 'absolute', left: '17%', top: '9%', flexDirection: 'row', gap: 7, alignItems: 'flex-start' },
  animeGloomLine: { width: 3, height: 27, borderRadius: 3, backgroundColor: 'rgba(103, 82, 120, 0.56)' },
  animeGloomLineShort: { height: 18 },

  pullStatus: { position: 'absolute', bottom: -2, left: 0, right: 0, alignItems: 'center', zIndex: 4 },
  pullStatusText: { color: '#8A6672', fontSize: 9, fontWeight: '900', backgroundColor: 'rgba(255,248,232,0.78)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10 },
  pullParticleBurst: { zIndex: 12 },
  timeParticleBurst: { zIndex: 7 },
  homeMoodBadge: { position: 'absolute', right: -4, top: 34, minHeight: 44, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: 'rgba(255,249,232,0.94)', borderWidth: 1.5, borderColor: '#E2B777', shadowColor: '#694B55', shadowOpacity: 0.18, shadowRadius: 5, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
  homeMoodBadgeText: { color: '#67465A', fontSize: 13, fontWeight: '900' },
  homeContextHint: { position: 'absolute', left: '50%', marginLeft: -105, bottom: -4, width: 210, minHeight: 50, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10, borderRadius: 10, backgroundColor: 'rgba(255,252,239,0.94)', borderWidth: 1.5, borderColor: '#DDAF86', shadowColor: '#704956', shadowOpacity: 0.16, shadowRadius: 5, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
  homeContextHintText: { color: '#654456', fontSize: 16, lineHeight: 22, fontWeight: '900', textAlign: 'center' },
  collectionProgressBadge: { position: 'absolute', right: 12, top: 8, minWidth: 58, minHeight: 44, paddingHorizontal: 8, alignItems: 'center', justifyContent: 'center', borderRadius: 10, borderWidth: 1.2, borderColor: '#D7B994', backgroundColor: 'rgba(255,250,233,0.92)' },
  collectionProgressBadgeComplete: { borderColor: '#74B89C', backgroundColor: 'rgba(232,250,239,0.96)', shadowColor: '#39775F', shadowOpacity: 0.18, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  collectionProgressBadgeText: { color: '#5D4657', fontSize: 10, fontWeight: '900' },
  gamePressed: { transform: [{ scale: 0.95 }], opacity: 0.9 },
  stageLight: { position: 'absolute', width: 300, height: 300, borderRadius: 160, backgroundColor: 'rgba(255,248,229,0.55)' },
  touchImage: { width: 285, height: 335 },
  touchBubble: { position: 'absolute', top: 15, left: 14, maxWidth: 180, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 16, backgroundColor: '#FFFDF5', borderWidth: 1, borderColor: '#E8CDB4', transform: [{ rotate: '-3deg' }] },
  touchBubbleText: { color: '#5E4057', fontSize: 12, fontWeight: '900' },
  touchHand: { position: 'absolute', right: 19, bottom: 21, color: '#F0B99E', fontSize: 54, fontWeight: '900', transform: [{ rotate: '-18deg' }], textShadowColor: 'rgba(89,55,63,0.22)', textShadowRadius: 3 },
  touchHearts: { position: 'absolute', bottom: 16, right: 16, flexDirection: 'row' },
  touchHeart: { color: '#D57889', fontSize: 21, marginLeft: 5 },
  touchTip: { marginTop: 12, padding: 12, borderRadius: 16, backgroundColor: '#F2E4E2', flexDirection: 'row', alignItems: 'center' },
  tipMobbyIcon: { width: 35, height: 35, marginRight: 7 },
  touchTipText: { flex: 1, color: '#906D77', fontSize: 13, fontWeight: '800', lineHeight: 19 },
  touchFooter: { color: '#AC8284', fontSize: 10, fontWeight: '800', textAlign: 'center', marginTop: 13 },
  bottomNav: { position: 'absolute', left: 8, width: DESIGN_WIDTH - 16, bottom: Platform.OS === 'web' ? 9 : 3, height: 74, shadowColor: '#624651', shadowOpacity: 0.16, shadowRadius: 9, shadowOffset: { width: 0, height: 4 }, elevation: 8 },
  bottomNavAsset: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  bottomNavSlotLayer: { position: 'absolute', top: 9, left: 0, right: 0, height: 55, flexDirection: 'row', zIndex: 1 },
  bottomNavSlot: { flex: 1, minWidth: 44, height: 55, borderRadius: 18, backgroundColor: 'rgba(255,241,215,0.96)', borderWidth: 1.2, borderColor: 'rgba(222,190,145,0.92)', shadowColor: '#B98D68', shadowOpacity: 0.08, shadowRadius: 2, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  bottomNavTabLayer: { position: 'absolute', top: 9, left: 0, right: 0, height: 55, flexDirection: 'row', zIndex: 2 },
  navTab: { flex: 1, minWidth: 44, height: 55, position: 'relative', borderRadius: 18, alignItems: 'center', justifyContent: 'center', outlineStyle: 'solid', outlineWidth: 0, outlineColor: 'transparent' },
  navTabPressed: { opacity: 0.72 },
  navIcon: { width: 24, height: 24, tintColor: '#A48189', marginBottom: 2 },
  navCaseIcon: { width: 22, height: 22 },
  navIconActive: { tintColor: '#705178' },
  navLabel: { color: '#80626B', fontSize: 9, fontWeight: '700' },
  navLabelActive: { color: '#694B70' },
  navIncidentBadge: { position: 'absolute', top: 1, right: 9, width: 16, height: 16, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#C65F6D', borderWidth: 1.2, borderColor: '#FFF8EB' },
  navIncidentBadgeText: { color: '#FFF8EC', fontSize: 9, lineHeight: 11, fontWeight: '900' },
  navDot: { position: 'absolute', bottom: 3, width: 4, height: 4, borderRadius: 2, backgroundColor: '#D17B8C' },
  pressed: { opacity: 0.9, transform: [{ translateY: 1 }, { scale: 0.95 }] },
});
