import { useEffect, useRef, useState } from 'react';
import { Animated, Image, StyleSheet, View, type ImageSourcePropType } from 'react-native';
import { Text } from '@/ui/layout/visualPrimitives';
import { MobbyAssetButton, MobbyAssetSelectable, MobbyAssetSurface } from '@/components/mobby-ui';

export type IncidentCasebookTab = 'active' | 'episodes' | 'relationships';
export type IncidentCasebookActiveEpisode = { title:string; chapter:string; targetName:string; targetImage:ImageSourcePropType; enemyName:string; enemyImage:ImageSourcePropType; progressLabel:string };
export type IncidentCasebookEpisodeEntry = { episodeId:string; chapter:string; title:string; synopsis:string; enemyName:string; targetName:string; keyVisual:ImageSourcePropType; memorableLine:string; relationship:string; endingLabel:string|null; unseenEndingLabel:string|null; playCount:number; unlocked:boolean };
export type IncidentCasebookRelationshipEntry = { id:string; enemyName:string; mobbyName:string; label:string; image:ImageSourcePropType };
export type IncidentCasebookActiveCase = IncidentCasebookActiveEpisode;
export type IncidentCasebookComicEntry = IncidentCasebookEpisodeEntry;
export type IncidentCasebookEnemyEntry = IncidentCasebookRelationshipEntry;
export type IncidentCasebookScreenProps = { activeEpisode:IncidentCasebookActiveEpisode|null; episodes:readonly IncidentCasebookEpisodeEntry[]; relationships:readonly IncidentCasebookRelationshipEntry[]; initialTab?:IncidentCasebookTab; onResume:()=>void; onRestart:()=>void; onStart:()=>void; onPlayEpisode:(episodeId:string)=>void; onClose:()=>void; entryNonce?:number };
const TABS:readonly {id:IncidentCasebookTab;label:string}[]=[{id:'active',label:'進行中'},{id:'episodes',label:'エピソード'},{id:'relationships',label:'関係性'}];

export function IncidentCasebookScreen({activeEpisode,episodes,relationships,initialTab='active',onResume,onRestart,onStart,onPlayEpisode,onClose,entryNonce=0}:IncidentCasebookScreenProps){
  const [tab,setTab]=useState(initialTab); useEffect(()=>setTab(initialTab),[initialTab]);
  const entryMotion = useRef(new Animated.Value(1)).current;
  useEffect(() => {
    entryMotion.stopAnimation();
    entryMotion.setValue(0);
    const animation = Animated.timing(entryMotion, { toValue: 1, duration: 460, useNativeDriver: typeof document === 'undefined' });
    animation.start();
    return () => animation.stop();
  }, [entryMotion, entryNonce]);
  return <Animated.View style={[styles.root, { opacity: entryMotion.interpolate({ inputRange: [0, 0.42, 1], outputRange: [0.5, 0.84, 1] }), transform: [{ translateY: entryMotion.interpolate({ inputRange: [0, 1], outputRange: [18, 0] }) }, { scale: entryMotion.interpolate({ inputRange: [0, 1], outputRange: [0.94, 1] }) }] }]}><View style={styles.header}><View><Text style={styles.eyebrow}>RELATIONSHIP ALBUM</Text><Text accessibilityRole="header" style={styles.heading}>関係性アルバム</Text></View><MobbyAssetButton accessibilityLabel="関係性アルバムを閉じる" tone="cream" onPress={onClose} style={styles.close} contentStyle={styles.closeContent}><Text style={styles.closeText}>×</Text></MobbyAssetButton></View>
    <View accessibilityRole="tablist" accessibilityLabel="関係性アルバムの表示内容" style={styles.tabs}>{TABS.map(item=><MobbyAssetSelectable key={item.id} variant="notice" accessibilityRole="tab" accessibilityLabel={item.label} selected={tab===item.id} onPress={()=>setTab(item.id)} style={styles.tab} contentStyle={styles.tabContent}><Text style={[styles.tabText,tab===item.id&&styles.tabTextOn]}>{item.label}</Text></MobbyAssetSelectable>)}</View>
    <View style={styles.content}>
      {tab==='active' ? activeEpisode ? <MobbyAssetSurface variant="darkCase" style={styles.card} contentStyle={styles.cardContent}><Text style={styles.kicker}>{activeEpisode.chapter}・{activeEpisode.progressLabel}</Text><Text style={styles.title}>{activeEpisode.title}</Text><View style={styles.pair}><Image accessible={false} source={activeEpisode.enemyImage} resizeMode="contain" style={styles.person}/><Text style={styles.cross}>×</Text><Image accessible={false} source={activeEpisode.targetImage} resizeMode="contain" style={styles.person}/></View><Text style={styles.meta}>{activeEpisode.enemyName} × {activeEpisode.targetName}</Text><MobbyAssetButton accessibilityLabel={`${activeEpisode.title}を続きから再生`} onPress={onResume}><Text style={styles.primaryText}>続きから</Text></MobbyAssetButton><MobbyAssetButton accessibilityLabel={`${activeEpisode.title}を最初から再生`} tone="cream" onPress={onRestart}><Text style={styles.secondaryText}>最初から</Text></MobbyAssetButton></MobbyAssetSurface> : <MobbyAssetSurface variant="darkCase" style={styles.card} contentStyle={styles.cardContent}><Text style={styles.title}>第1話を始めよう</Text><Text style={styles.body}>金庫破りとれおもびの、妙に優雅なティータイム。</Text><MobbyAssetButton accessibilityLabel="第1話を開始" onPress={onStart}><Text style={styles.primaryText}>第1話を開始</Text></MobbyAssetButton></MobbyAssetSurface> : null}
      {tab==='episodes' ? episodes.map(entry=><MobbyAssetSurface key={entry.episodeId} variant="darkCase" style={[styles.card,!entry.unlocked&&styles.cardLocked]} contentStyle={styles.cardContent}><Text style={styles.kicker}>{entry.chapter}・{entry.unlocked ? `再生 ${entry.playCount}回` : '前話クリアで解放'}</Text><Text style={styles.title}>{entry.unlocked ? entry.title : '？？？'}</Text>{entry.unlocked?<><Image accessible={false} source={entry.keyVisual} resizeMode="cover" style={styles.visual}/><Text style={styles.meta}>{entry.enemyName} × {entry.targetName}</Text><Text style={styles.body}>{entry.synopsis}</Text>{entry.playCount>0?<><Text style={styles.quote}>「{entry.memorableLine}」</Text><Text style={styles.relationship}>関係性：{entry.relationship}</Text><Text style={styles.ending}>閲覧済み：{entry.endingLabel}</Text><Text style={styles.locked}>{entry.unseenEndingLabel ? `未閲覧：${entry.unseenEndingLabel}` : '両方のendingを閲覧済み'}</Text></>:<Text style={styles.locked}>未再生・ending未閲覧</Text>}<MobbyAssetButton accessibilityLabel={`${entry.title}を最初から再生`} tone="cream" onPress={()=>onPlayEpisode(entry.episodeId)}><Text style={styles.secondaryText}>最初から再生</Text></MobbyAssetButton></>:<Text style={styles.locked}>第1話から順番にエピソードを完走してください。</Text>}</MobbyAssetSurface>) : null}
      {tab==='relationships' ? relationships.length ? relationships.map(entry=><MobbyAssetSurface key={entry.id} variant="notice" style={styles.relationshipCard} contentStyle={styles.relationshipCardContent}><Image accessible={false} source={entry.image} resizeMode="contain" style={styles.relationshipImage}/><View style={styles.relationshipCopy}><Text style={styles.meta}>{entry.enemyName} × {entry.mobbyName}</Text><Text style={styles.relationship}>{entry.label}</Text></View></MobbyAssetSurface>) : <Text style={styles.empty}>関係性はエピソード完走後に記録されます。</Text> : null}
    </View>
  </Animated.View>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#F9EFDF',paddingTop:10},header:{paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{color:'#A45A6D',fontSize: 12,fontWeight:'900'},heading:{color:'#4D3046',fontSize:25,fontWeight:'900'},close:{width:44,height:44,overflow:'hidden'},closeContent:{width:44,height:44,alignItems:'center',justifyContent:'center'},closeText:{fontSize:28,color:'#69475F'},tabs:{flexDirection:'row',gap:5,padding:12},tab:{flex:1,minHeight:44},tabContent:{minHeight:44,alignItems:'center',justifyContent:'center',paddingHorizontal:10},tabText:{color:'#725468',fontWeight:'900'},tabTextOn:{color:'#694B70'},content:{flex:1,padding:14,paddingBottom:100,gap:14,overflow:'hidden'},card:{minHeight:160},cardContent:{padding:22,gap:10},cardLocked:{opacity:.72},kicker:{color:'#A6566B',fontWeight:'900'},title:{color:'#4B3044',fontSize:21,fontWeight:'900'},pair:{height:170,flexDirection:'row',alignItems:'center',justifyContent:'center'},person:{width:130,height:165},cross:{fontSize:26,color:'#C16879',fontWeight:'900'},meta:{color:'#70485E',fontSize:15,fontWeight:'900'},body:{color:'#674F5B',lineHeight:20},quote:{color:'#8F5267',fontWeight:'800',fontStyle:'italic'},relationship:{color:'#4F725C',fontWeight:'900'},ending:{color:'#7B5368',fontWeight:'800'},locked:{color:'#A48A94'},visual:{width:'100%',height:150,borderRadius:14},primary:{minHeight:50},primaryText:{color:'#FFF',fontWeight:'900',fontSize:16},secondary:{minHeight:44},secondaryText:{color:'#70485E',fontWeight:'900'},relationshipCard:{minHeight:120},relationshipCardContent:{minHeight:120,flexDirection:'row',alignItems:'center',padding:16},relationshipImage:{width:90,height:100},relationshipCopy:{flex:1,gap:6},empty:{color:'#806676',textAlign:'center',padding:30}});
