import { useEffect, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View, type ImageSourcePropType } from 'react-native';

export type IncidentCasebookTab = 'active' | 'episodes' | 'relationships';
export type IncidentCasebookActiveEpisode = { title:string; chapter:string; targetName:string; targetImage:ImageSourcePropType; enemyName:string; enemyImage:ImageSourcePropType; progressLabel:string };
export type IncidentCasebookEpisodeEntry = { episodeId:string; chapter:string; title:string; synopsis:string; enemyName:string; targetName:string; keyVisual:ImageSourcePropType; memorableLine:string; relationship:string; endingLabel:string|null; unseenEndingLabel:string|null; playCount:number; unlocked:boolean };
export type IncidentCasebookRelationshipEntry = { id:string; enemyName:string; mobbyName:string; label:string; image:ImageSourcePropType };
export type IncidentCasebookActiveCase = IncidentCasebookActiveEpisode;
export type IncidentCasebookComicEntry = IncidentCasebookEpisodeEntry;
export type IncidentCasebookEnemyEntry = IncidentCasebookRelationshipEntry;
export type IncidentCasebookScreenProps = { activeEpisode:IncidentCasebookActiveEpisode|null; episodes:readonly IncidentCasebookEpisodeEntry[]; relationships:readonly IncidentCasebookRelationshipEntry[]; initialTab?:IncidentCasebookTab; onResume:()=>void; onRestart:()=>void; onStart:()=>void; onPlayEpisode:(episodeId:string)=>void; onClose:()=>void };
const TABS:readonly {id:IncidentCasebookTab;label:string}[]=[{id:'active',label:'進行中'},{id:'episodes',label:'エピソード'},{id:'relationships',label:'関係性'}];

export function IncidentCasebookScreen({activeEpisode,episodes,relationships,initialTab='active',onResume,onRestart,onStart,onPlayEpisode,onClose}:IncidentCasebookScreenProps){
  const [tab,setTab]=useState(initialTab); useEffect(()=>setTab(initialTab),[initialTab]);
  return <View style={styles.root}><View style={styles.header}><View><Text style={styles.eyebrow}>RELATIONSHIP CASEBOOK</Text><Text style={styles.heading}>関係性事件簿</Text></View><Pressable accessibilityRole="button" onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View>
    <View style={styles.tabs}>{TABS.map(item=><Pressable key={item.id} accessibilityRole="tab" accessibilityState={{selected:tab===item.id}} onPress={()=>setTab(item.id)} style={[styles.tab,tab===item.id&&styles.tabOn]}><Text style={[styles.tabText,tab===item.id&&styles.tabTextOn]}>{item.label}</Text></Pressable>)}</View>
    <ScrollView contentContainerStyle={styles.content}>
      {tab==='active' ? activeEpisode ? <View style={styles.card}><Text style={styles.kicker}>{activeEpisode.chapter}・{activeEpisode.progressLabel}</Text><Text style={styles.title}>{activeEpisode.title}</Text><View style={styles.pair}><Image source={activeEpisode.enemyImage} resizeMode="contain" style={styles.person}/><Text style={styles.cross}>×</Text><Image source={activeEpisode.targetImage} resizeMode="contain" style={styles.person}/></View><Text style={styles.meta}>{activeEpisode.enemyName} × {activeEpisode.targetName}</Text><Pressable onPress={onResume} style={styles.primary}><Text style={styles.primaryText}>続きから</Text></Pressable><Pressable onPress={onRestart} style={styles.secondary}><Text style={styles.secondaryText}>最初から</Text></Pressable></View> : <View style={styles.card}><Text style={styles.title}>第1話を始めよう</Text><Text style={styles.body}>金庫破りとれおもびの、妙に優雅な犯行事件。</Text><Pressable onPress={onStart} style={styles.primary}><Text style={styles.primaryText}>第1話を開始</Text></Pressable></View> : null}
      {tab==='episodes' ? episodes.map(entry=><View key={entry.episodeId} style={[styles.card,!entry.unlocked&&styles.cardLocked]}><Text style={styles.kicker}>{entry.chapter}・{entry.unlocked ? `再生 ${entry.playCount}回` : '前話クリアで解放'}</Text><Text style={styles.title}>{entry.unlocked ? entry.title : '？？？'}</Text>{entry.unlocked?<><Image source={entry.keyVisual} resizeMode="cover" style={styles.visual}/><Text style={styles.meta}>{entry.enemyName} × {entry.targetName}</Text><Text style={styles.body}>{entry.synopsis}</Text>{entry.playCount>0?<><Text style={styles.quote}>「{entry.memorableLine}」</Text><Text style={styles.relationship}>関係性：{entry.relationship}</Text><Text style={styles.ending}>閲覧済み：{entry.endingLabel}</Text><Text style={styles.locked}>{entry.unseenEndingLabel ? `未閲覧：${entry.unseenEndingLabel}` : '両方のendingを閲覧済み'}</Text></>:<Text style={styles.locked}>未再生・ending未閲覧</Text>}<Pressable onPress={()=>onPlayEpisode(entry.episodeId)} style={styles.secondary}><Text style={styles.secondaryText}>最初から再生</Text></Pressable></>:<Text style={styles.locked}>第1話から順番にエピソードを完走してください。</Text>}</View>) : null}
      {tab==='relationships' ? relationships.length ? relationships.map(entry=><View key={entry.id} style={styles.relationshipCard}><Image source={entry.image} resizeMode="contain" style={styles.relationshipImage}/><View style={styles.relationshipCopy}><Text style={styles.meta}>{entry.enemyName} × {entry.mobbyName}</Text><Text style={styles.relationship}>{entry.label}</Text></View></View>) : <Text style={styles.empty}>関係性はエピソード完走後に記録されます。</Text> : null}
    </ScrollView>
  </View>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#F9EFDF',paddingTop:10},header:{paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{color:'#A45A6D',fontSize:10,fontWeight:'900'},heading:{color:'#4D3046',fontSize:25,fontWeight:'900'},close:{width:44,height:44,alignItems:'center',justifyContent:'center'},closeText:{fontSize:28,color:'#69475F'},tabs:{flexDirection:'row',gap:5,padding:12},tab:{flex:1,minHeight:42,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'#EAD9D0'},tabOn:{backgroundColor:'#754F70'},tabText:{color:'#725468',fontWeight:'900'},tabTextOn:{color:'#FFF'},content:{padding:14,paddingBottom:100,gap:14},card:{borderRadius:20,backgroundColor:'#FFF9EF',padding:16,gap:10,borderWidth:1,borderColor:'#E3CABE'},cardLocked:{opacity:.72},kicker:{color:'#A6566B',fontWeight:'900'},title:{color:'#4B3044',fontSize:21,fontWeight:'900'},pair:{height:170,flexDirection:'row',alignItems:'center',justifyContent:'center'},person:{width:130,height:165},cross:{fontSize:26,color:'#C16879',fontWeight:'900'},meta:{color:'#70485E',fontSize:15,fontWeight:'900'},body:{color:'#674F5B',lineHeight:20},quote:{color:'#8F5267',fontWeight:'800',fontStyle:'italic'},relationship:{color:'#4F725C',fontWeight:'900'},ending:{color:'#7B5368',fontWeight:'800'},locked:{color:'#A48A94'},visual:{width:'100%',height:150,borderRadius:14},primary:{minHeight:50,borderRadius:15,backgroundColor:'#D65E73',alignItems:'center',justifyContent:'center'},primaryText:{color:'#FFF',fontWeight:'900',fontSize:16},secondary:{minHeight:44,borderRadius:14,borderWidth:1,borderColor:'#B98B99',alignItems:'center',justifyContent:'center'},secondaryText:{color:'#70485E',fontWeight:'900'},relationshipCard:{flexDirection:'row',alignItems:'center',borderRadius:18,backgroundColor:'#FFF9EF',padding:12},relationshipImage:{width:90,height:100},relationshipCopy:{flex:1,gap:6},empty:{color:'#806676',textAlign:'center',padding:30}});
